// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqCreateOfficialAccount : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,0,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(sex,setSex:)) JceInt16 JV2_PROP_NM(r,1,sex);
@property (nonatomic, assign, JV2_PROP_GS_V2(teacherauth,setTeacherauth:)) JceInt16 JV2_PROP_NM(r,2,teacherauth);
@property (nonatomic, retain, JV2_PROP_GS_V2(photo,setPhoto:)) NSString* JV2_PROP_NM(r,3,photo);

@end
