// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqGetChildFocusUser.h"

@implementation ApolloTReqGetChildFocusUser

@synthesize JV2_PROP_NM(r,0,childUid);

+ (void)initialize
{
    if (self == [ApolloTReqGetChildFocusUser class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(childUid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqGetChildFocusUser";
}

@end
