// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTAuthTeacherApplication.h"

@implementation ApolloTAuthTeacherApplication

@synthesize JV2_PROP_NM(r,0,id);
@synthesize JV2_PROP_NM(r,1,uid);
@synthesize JV2_PROP_NM(r,2,name);
@synthesize JV2_PROP_NM(r,3,mobilePhone);
@synthesize JV2_PROP_NM(r,4,sex);
@synthesize JV2_PROP_NM(r,5,pic);
@synthesize JV2_PROP_NM(r,6,creationtime);
@synthesize JV2_PROP_NM(r,7,audittime);
@synthesize JV2_PROP_NM(r,8,auditstatus);
@synthesize JV2_PROP_NM(r,9,desc);

+ (void)initialize
{
    if (self == [ApolloTAuthTeacherApplication class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(mobilePhone) = DefaultJceString;
        JV2_PROP(pic) = DefaultJceString;
        JV2_PROP(desc) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TAuthTeacherApplication";
}

@end
