// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneComment.h"
#import "ApolloTZoneLikerObject.h"

@interface ApolloTRespCommentList : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vComments,setVComments:)) NSArray* JV2_PROP_EX(r,0,vComments,VOApolloTZoneComment);
@property (nonatomic, retain, JV2_PROP_GS_V2(vhotComments,setVhotComments:)) NSArray* JV2_PROP_EX(o,1,vhotComments,VOApolloTZoneComment);
@property (nonatomic, assign, JV2_PROP_GS_V2(commentNum,setCommentNum:)) JceInt32 JV2_PROP_NM(o,2,commentNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(likeNum,setLikeNum:)) JceInt32 JV2_PROP_NM(o,3,likeNum);
@property (nonatomic, retain, JV2_PROP_GS_V2(likers,setLikers:)) NSArray* JV2_PROP_EX(o,4,likers,VOApolloTZoneLikerObject);

@end
