// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneObject.h"
#import "ApolloTZonePictureText.h"

@interface ApolloTZoneMsgContent : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(content,setContent:)) NSArray* JV2_PROP_EX(r,0,content,VOApolloTZonePictureText);
@property (nonatomic, retain, JV2_PROP_GS_V2(toClass,setToClass:)) ApolloTZoneObject* JV2_PROP_NM(o,1,toClass);
@property (nonatomic, assign, JV2_PROP_GS_V2(openStatus,setOpenStatus:)) JceInt32 JV2_PROP_NM(o,2,openStatus);
@property (nonatomic, retain, JV2_PROP_GS_V2(tagid,setTagid:)) NSString* JV2_PROP_NM(o,3,tagid);

@end
