// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqModifyRobotStatistics.h"

@implementation ApolloTReqModifyRobotStatistics

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,objectId);
@synthesize JV2_PROP_NM(r,2,type);
@synthesize JV2_PROP_NM(r,3,modifyType);
@synthesize JV2_PROP_NM(r,4,count);

+ (void)initialize
{
    if (self == [ApolloTReqModifyRobotStatistics class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqModifyRobotStatistics";
}

@end
