// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqGetMallActivated : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sDeviceID,setSDeviceID:)) NSString* JV2_PROP_NM(r,0,sDeviceID);
@property (nonatomic, retain, JV2_PROP_GS_V2(sPhonetype,setSPhonetype:)) NSString* JV2_PROP_NM(r,1,sPhonetype);

@end
