// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTRespGetNoticeboxs.h"

@implementation ApolloTRespGetNoticeboxs

@synthesize JV2_PROP_EX(r,0,vNoticeboxs,VOApolloTNoticeMessageBox);

+ (void)initialize
{
    if (self == [ApolloTRespGetNoticeboxs class]) {
        [ApolloTNoticeMessageBox initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vNoticeboxs) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetNoticeboxs";
}

@end
