// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespPublishTopAdv : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(aid,setAid:)) JceInt64 JV2_PROP_NM(r,0,aid);

@end
