// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/audit.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTClientReceiveAuditIndex.h"

@interface ApolloTRespPushAudit : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vRespIndex,setVRespIndex:)) NSArray* JV2_PROP_EX(r,0,vRespIndex,VOApolloTClientReceiveAuditIndex);

@end
