// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTClassCardInfo : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(r,0,cid);
@property (nonatomic, retain, JV2_PROP_GS_V2(cName,setCName:)) NSString* JV2_PROP_NM(r,1,cName);
@property (nonatomic, retain, JV2_PROP_GS_V2(classCode,setClassCode:)) NSString* JV2_PROP_NM(r,2,classCode);
@property (nonatomic, retain, JV2_PROP_GS_V2(masterName,setMasterName:)) NSString* JV2_PROP_NM(r,3,masterName);
@property (nonatomic, assign, JV2_PROP_GS_V2(joinverify,setJoinverify:)) JceInt16 JV2_PROP_NM(o,4,joinverify);

@end
