// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqAuthTeacherApplication.h"

@implementation ApolloTReqAuthTeacherApplication

@synthesize JV2_PROP_NM(r,0,id);
@synthesize JV2_PROP_NM(r,1,auditstatus);
@synthesize JV2_PROP_NM(r,2,desc);

+ (void)initialize
{
    if (self == [ApolloTReqAuthTeacherApplication class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(desc) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqAuthTeacherApplication";
}

@end
