// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClientProto.jce'
// **********************************************************************

#import "ApolloTMsgTest.h"

@implementation ApolloTMsgTest

@synthesize JV2_PROP_NM(r,0,iSec);
@synthesize JV2_PROP_NM(r,1,iUSec);

+ (void)initialize
{
    if (self == [ApolloTMsgTest class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TMsgTest";
}

@end
