// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Package.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloSHARE_SOURCE.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation ApolloSHARE_SOURCEHelper

+ (NSString *)etos:(ApolloSHARE_SOURCE)e
{
    switch(e){
        case ApolloSHARE_SOURCE_Wechat: return @"ApolloSHARE_SOURCE_Wechat";
        case ApolloSHARE_SOURCE_Friendster: return @"ApolloSHARE_SOURCE_Friendster";
        case ApolloSHARE_SOURCE_QQ: return @"ApolloSHARE_SOURCE_QQ";
        case ApolloSHARE_SOURCE_Weibo: return @"ApolloSHARE_SOURCE_Weibo";
        case ApolloSHARE_SOURCE_QQzone: return @"ApolloSHARE_SOURCE_QQzone";
        case ApolloSHARE_SOURCE_TencentWeibo: return @"ApolloSHARE_SOURCE_TencentWeibo";
        default: return @"";
    }
}

+ (ApolloSHARE_SOURCE)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"ApolloSHARE_SOURCE_Wechat")) return ApolloSHARE_SOURCE_Wechat;
    if(isJceEnumStringEqual(s, @"ApolloSHARE_SOURCE_Friendster")) return ApolloSHARE_SOURCE_Friendster;
    if(isJceEnumStringEqual(s, @"ApolloSHARE_SOURCE_QQ")) return ApolloSHARE_SOURCE_QQ;
    if(isJceEnumStringEqual(s, @"ApolloSHARE_SOURCE_Weibo")) return ApolloSHARE_SOURCE_Weibo;
    if(isJceEnumStringEqual(s, @"ApolloSHARE_SOURCE_QQzone")) return ApolloSHARE_SOURCE_QQzone;
    if(isJceEnumStringEqual(s, @"ApolloSHARE_SOURCE_TencentWeibo")) return ApolloSHARE_SOURCE_TencentWeibo;
    return NSIntegerMin;
}

@end

#endif
