// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqWeiXiCloseOrder : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(out_trade_no,setOut_trade_no:)) NSString* JV2_PROP_NM(o,0,out_trade_no);

@end
