// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTFamily.h"

@implementation ApolloTFamily

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_NM(o,2,photo);
@synthesize JV2_PROP_NM(r,3,relation);
@synthesize JV2_PROP_NM(r,4,guardianType);
@synthesize JV2_PROP_NM(o,5,mobilePhone);
@synthesize JV2_PROP_NM(o,6,icon);
@synthesize JV2_PROP_NM(o,7,loginstatus);

+ (void)initialize
{
    if (self == [ApolloTFamily class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(photo) = DefaultJceString;
        JV2_PROP(relation) = DefaultJceString;
        JV2_PROP(mobilePhone) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TFamily";
}

@end
