// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/connect.jce'
// **********************************************************************

#import "ApolloTReqAuth.h"

@implementation ApolloTReqAuth

@synthesize JV2_PROP_NM(r,0,sVer);
@synthesize JV2_PROP_NM(r,1,nClientType);
@synthesize JV2_PROP_NM(r,2,sDeviceID);
@synthesize JV2_PROP_NM(r,3,sessionCode);
@synthesize JV2_PROP_NM(o,4,timestamp);
@synthesize JV2_PROP_NM(o,5,apnsToken);

+ (void)initialize
{
    if (self == [ApolloTReqAuth class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sVer) = DefaultJceString;
        JV2_PROP(sDeviceID) = DefaultJceString;
        JV2_PROP(sessionCode) = DefaultJceString;
        JV2_PROP(apnsToken) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqAuth";
}

@end
