// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqBindingThirdAccount : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(flag,setFlag:)) JceInt32 JV2_PROP_NM(r,0,flag);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt32 JV2_PROP_NM(r,1,type);
@property (nonatomic, retain, JV2_PROP_GS_V2(account,setAccount:)) NSString* JV2_PROP_NM(r,2,account);
@property (nonatomic, retain, JV2_PROP_GS_V2(nick,setNick:)) NSString* JV2_PROP_NM(r,3,nick);
@property (nonatomic, retain, JV2_PROP_GS_V2(photo,setPhoto:)) NSString* JV2_PROP_NM(r,4,photo);
@property (nonatomic, assign, JV2_PROP_GS_V2(sex,setSex:)) JceInt16 JV2_PROP_NM(r,5,sex);

@end
