// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqBatchUidJoinActive.h"

@implementation ApolloTReqBatchUidJoinActive

@synthesize JV2_PROP_EX(r,0,vecReqJoinActive,VOApolloTReqJoinClassFeeCardActivity);

+ (void)initialize
{
    if (self == [ApolloTReqBatchUidJoinActive class]) {
        [ApolloTReqJoinClassFeeCardActivity initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vecReqJoinActive) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqBatchUidJoinActive";
}

@end
