// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespOmsSearchUserLoginStatus : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(mapUidStatus,setMapUidStatus:)) NSDictionary* JV2_PROP_EX(r,0,mapUidStatus,M09ONSStringONSNumber);

@end
