// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Package.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloTZoneHotType_E_COM = 1,
    ApolloTZoneHotType_E_ADVERT = 2,
    ApolloTZoneHotType_E_Channel
};
#define ApolloTZoneHotType NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloTZoneHotTypeHelper: JceEnumHelper

+ (NSString *)etos:(ApolloTZoneHotType)e;
+ (ApolloTZoneHotType)stoe:(NSString *)s;

@end

#endif
