// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTChildSchoolAndClassInfo.h"

@interface ApolloTRespGetChildInfo : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(photo,setPhoto:)) NSString* JV2_PROP_NM(r,2,photo);
@property (nonatomic, retain, JV2_PROP_GS_V2(vSchoolAndClassesInfo,setVSchoolAndClassesInfo:)) NSArray* JV2_PROP_EX(r,3,vSchoolAndClassesInfo,VOApolloTChildSchoolAndClassInfo);

@end
