// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqSendSmsInvitation : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vMobilePhone,setVMobilePhone:)) NSArray* JV2_PROP_EX(r,0,vMobilePhone,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(content,setContent:)) NSString* JV2_PROP_NM(r,1,content);

@end
