// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqOmsEditSchool : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(sid,setSid:)) JceInt32 JV2_PROP_NM(r,0,sid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(aid,setAid:)) JceInt32 JV2_PROP_NM(r,2,aid);
@property (nonatomic, retain, JV2_PROP_GS_V2(stid,setStid:)) NSString* JV2_PROP_NM(r,3,stid);
@property (nonatomic, assign, JV2_PROP_GS_V2(isjoin,setIsjoin:)) JceInt32 JV2_PROP_NM(r,4,isjoin);

@end
