// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "ApolloTRespCardAmountList.h"

@implementation ApolloTRespCardAmountList

@synthesize JV2_PROP_EX(r,0,amountList,VOApolloTClassFeeCardAmountList);

+ (void)initialize
{
    if (self == [ApolloTRespCardAmountList class]) {
        [ApolloTClassFeeCardAmountList initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(amountList) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespCardAmountList";
}

@end
