// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTRespPersonHomePageLikeList.h"

@implementation ApolloTRespPersonHomePageLikeList

@synthesize JV2_PROP_NM(r,0,likeNum);
@synthesize JV2_PROP_EX(r,1,likes,VOApolloTZoneLikerListUser);

+ (void)initialize
{
    if (self == [ApolloTRespPersonHomePageLikeList class]) {
        [ApolloTZoneLikerListUser initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(likes) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespPersonHomePageLikeList";
}

@end
