// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "ApolloTRespTotalMoneyAndHead.h"

@implementation ApolloTRespTotalMoneyAndHead

@synthesize JV2_PROP_NM(r,0,totalMoney);
@synthesize JV2_PROP_NM(r,1,totalHead);

+ (void)initialize
{
    if (self == [ApolloTRespTotalMoneyAndHead class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespTotalMoneyAndHead";
}

@end
