// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTUser : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(sex,setSex:)) JceInt16 JV2_PROP_NM(r,2,sex);
@property (nonatomic, retain, JV2_PROP_GS_V2(icon,setIcon:)) NSString* JV2_PROP_NM(r,3,icon);
@property (nonatomic, retain, JV2_PROP_GS_V2(signature,setSignature:)) NSString* JV2_PROP_NM(r,4,signature);
@property (nonatomic, retain, JV2_PROP_GS_V2(mobilephone,setMobilephone:)) NSString* JV2_PROP_NM(r,5,mobilephone);
@property (nonatomic, retain, JV2_PROP_GS_V2(address,setAddress:)) NSString* JV2_PROP_NM(r,6,address);
@property (nonatomic, assign, JV2_PROP_GS_V2(identity,setIdentity:)) JceInt32 JV2_PROP_NM(r,7,identity);
@property (nonatomic, assign, JV2_PROP_GS_V2(addressId,setAddressId:)) JceInt32 JV2_PROP_NM(o,8,addressId);
@property (nonatomic, assign, JV2_PROP_GS_V2(teacherauth,setTeacherauth:)) JceInt16 JV2_PROP_NM(o,9,teacherauth);
@property (nonatomic, assign, JV2_PROP_GS_V2(issmsauth,setIssmsauth:)) JceInt16 JV2_PROP_NM(o,10,issmsauth);
@property (nonatomic, assign, JV2_PROP_GS_V2(usertype,setUsertype:)) JceInt16 JV2_PROP_NM(o,11,usertype);
@property (nonatomic, retain, JV2_PROP_GS_V2(userschoolname,setUserschoolname:)) NSString* JV2_PROP_NM(o,12,userschoolname);

@end
