// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/PullNewUserActivity.jce'
// **********************************************************************

#import "ApolloTRespPullNewCidUpToStandard.h"

@implementation ApolloTRespPullNewCidUpToStandard

@synthesize JV2_PROP_NM(r,0,b);

+ (void)initialize
{
    if (self == [ApolloTRespPullNewCidUpToStandard class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespPullNewCidUpToStandard";
}

@end
