// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqClassOutOfSchool : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(classcode,setClasscode:)) NSString* JV2_PROP_NM(r,0,classcode);
@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(r,1,cid);
@property (nonatomic, assign, JV2_PROP_GS_V2(sid,setSid:)) JceInt32 JV2_PROP_NM(r,2,sid);

@end
