// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "ApolloTAdPlace.h"

@implementation ApolloTAdPlace

@synthesize JV2_PROP_NM(r,0,adId);
@synthesize JV2_PROP_NM(r,1,adType);
@synthesize JV2_PROP_NM(o,2,title);
@synthesize JV2_PROP_NM(o,3,pic);
@synthesize JV2_PROP_NM(o,4,details);
@synthesize JV2_PROP_NM(o,5,money);
@synthesize JV2_PROP_NM(o,6,dayclick);
@synthesize JV2_PROP_NM(o,7,daymaxclick);
@synthesize JV2_PROP_NM(o,8,adNo);

+ (void)initialize
{
    if (self == [ApolloTAdPlace class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(title) = DefaultJceString;
        JV2_PROP(pic) = DefaultJceString;
        JV2_PROP(details) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TAdPlace";
}

@end
