// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "ApolloTReqClassFeeDetail.h"

@implementation ApolloTReqClassFeeDetail

@synthesize JV2_PROP_NM(r,0,iCid);
@synthesize JV2_PROP_NM(r,1,lOrderNum);
@synthesize JV2_PROP_NM(r,2,iNum);
@synthesize JV2_PROP_NM(r,3,sDirection);

+ (void)initialize
{
    if (self == [ApolloTReqClassFeeDetail class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqClassFeeDetail";
}

@end
