// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTNoticeReadTime.h"
#import "ApolloTStudent.h"
#import "ApolloTTeacher.h"

@interface ApolloTRespAppSendNoticeDetail : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(teacherRead,setTeacherRead:)) NSArray* JV2_PROP_EX(r,0,teacherRead,VOApolloTTeacher);
@property (nonatomic, retain, JV2_PROP_GS_V2(teacherUnread,setTeacherUnread:)) NSArray* JV2_PROP_EX(r,1,teacherUnread,VOApolloTTeacher);
@property (nonatomic, retain, JV2_PROP_GS_V2(studentRead,setStudentRead:)) NSArray* JV2_PROP_EX(r,2,studentRead,VOApolloTStudent);
@property (nonatomic, retain, JV2_PROP_GS_V2(studentUnread,setStudentUnread:)) NSArray* JV2_PROP_EX(r,3,studentUnread,VOApolloTStudent);
@property (nonatomic, assign, JV2_PROP_GS_V2(totalStudent,setTotalStudent:)) JceInt32 JV2_PROP_NM(o,4,totalStudent);
@property (nonatomic, retain, JV2_PROP_GS_V2(readTime,setReadTime:)) NSArray* JV2_PROP_EX(o,5,readTime,VOApolloTNoticeReadTime);

@end
