// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTRespClassGroups.h"

@implementation ApolloTRespClassGroups

@synthesize JV2_PROP_EX(r,0,vClassGroups,VOApolloTClassGroup);

+ (void)initialize
{
    if (self == [ApolloTRespClassGroups class]) {
        [ApolloTClassGroup initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vClassGroups) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespClassGroups";
}

@end
