// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Bean.jce'
// **********************************************************************

#import "ApolloTRespAcquireBeanLog.h"

@implementation ApolloTRespAcquireBeanLog

@synthesize JV2_PROP_EX(r,0,vBeanLog,VOApolloTBeanOperationRecord);

+ (void)initialize
{
    if (self == [ApolloTRespAcquireBeanLog class]) {
        [ApolloTBeanOperationRecord initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vBeanLog) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespAcquireBeanLog";
}

@end
