// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTImportClassStudentGuardianItem.h"

@implementation ApolloTImportClassStudentGuardianItem

@synthesize JV2_PROP_NM(r,0,classcode);
@synthesize JV2_PROP_NM(r,1,studentName);
@synthesize JV2_PROP_NM(r,2,mobilePhone);
@synthesize JV2_PROP_EX(r,3,vMobilePhones,VONSString);

+ (void)initialize
{
    if (self == [ApolloTImportClassStudentGuardianItem class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(classcode) = DefaultJceString;
        JV2_PROP(studentName) = DefaultJceString;
        JV2_PROP(mobilePhone) = DefaultJceString;
        JV2_PROP(vMobilePhones) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TImportClassStudentGuardianItem";
}

@end
