// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTZoneLikerObject : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(photo,setPhoto:)) NSString* JV2_PROP_NM(r,2,photo);
@property (nonatomic, assign, JV2_PROP_GS_V2(authentication,setAuthentication:)) JceInt32 JV2_PROP_NM(r,3,authentication);
@property (nonatomic, assign, JV2_PROP_GS_V2(sendTime,setSendTime:)) JceInt64 JV2_PROP_NM(o,4,sendTime);

@end
