// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/audit.jce'
// **********************************************************************

#import "ApolloTRespQueryAuditRecord.h"

@implementation ApolloTRespQueryAuditRecord

@synthesize JV2_PROP_EX(r,0,vAuditRecord,VOApolloTAuditRecord);
@synthesize JV2_PROP_NM(r,1,total);

+ (void)initialize
{
    if (self == [ApolloTRespQueryAuditRecord class]) {
        [ApolloTAuditRecord initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vAuditRecord) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespQueryAuditRecord";
}

@end
