// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTNotice.h"

@interface ApolloTRespGetSendedNotices : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vNotice,setVNotice:)) NSArray* JV2_PROP_EX(r,0,vNotice,VOApolloTNotice);
@property (nonatomic, assign, JV2_PROP_GS_V2(total,setTotal:)) JceInt64 JV2_PROP_NM(r,1,total);

@end
