// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTClassFeeCardRolloutLog : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(strName,setStrName:)) NSString* JV2_PROP_NM(r,1,strName);
@property (nonatomic, assign, JV2_PROP_GS_V2(sEventID,setSEventID:)) JceInt16 JV2_PROP_NM(r,2,sEventID);
@property (nonatomic, assign, JV2_PROP_GS_V2(dValue,setDValue:)) JceInt32 JV2_PROP_NM(r,3,dValue);
@property (nonatomic, assign, JV2_PROP_GS_V2(timestamp,setTimestamp:)) JceInt32 JV2_PROP_NM(r,4,timestamp);
@property (nonatomic, retain, JV2_PROP_GS_V2(strRemark,setStrRemark:)) NSString* JV2_PROP_NM(o,5,strRemark);
@property (nonatomic, assign, JV2_PROP_GS_V2(lOrderNum,setLOrderNum:)) JceInt64 JV2_PROP_NM(o,6,lOrderNum);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCardidList,setVCardidList:)) NSArray* JV2_PROP_EX(o,7,vCardidList,VONSNumber);

@end
