// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTClassFeeCardAmountList.h"

@interface ApolloTRespCardAmountList : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(amountList,setAmountList:)) NSArray* JV2_PROP_EX(r,0,amountList,VOApolloTClassFeeCardAmountList);

@end
