// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTStructUserChild.h"

@implementation ApolloTStructUserChild

@synthesize JV2_PROP_NM(r,0,studentid);
@synthesize JV2_PROP_NM(r,1,role);
@synthesize JV2_PROP_NM(r,2,main);

+ (void)initialize
{
    if (self == [ApolloTStructUserChild class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(studentid) = DefaultJceString;
        JV2_PROP(role) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TStructUserChild";
}

@end
