// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloAD_TYPE.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation ApolloAD_TYPEHelper

+ (NSString *)etos:(ApolloAD_TYPE)e
{
    switch(e){
        case ApolloAD_TYPE_TYPE_OWN: return @"ApolloAD_TYPE_TYPE_OWN";
        case ApolloAD_TYPE_TYPE_ADSENSE: return @"ApolloAD_TYPE_TYPE_ADSENSE";
        default: return @"";
    }
}

+ (ApolloAD_TYPE)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"ApolloAD_TYPE_TYPE_OWN")) return ApolloAD_TYPE_TYPE_OWN;
    if(isJceEnumStringEqual(s, @"ApolloAD_TYPE_TYPE_ADSENSE")) return ApolloAD_TYPE_TYPE_ADSENSE;
    return NSIntegerMin;
}

@end

#endif
