// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "ApolloTReqWeiXiQueryOrder.h"

@implementation ApolloTReqWeiXiQueryOrder

@synthesize JV2_PROP_NM(r,0,transaction_id);
@synthesize JV2_PROP_NM(o,1,out_trade_no);

+ (void)initialize
{
    if (self == [ApolloTReqWeiXiQueryOrder class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(transaction_id) = DefaultJceString;
        JV2_PROP(out_trade_no) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqWeiXiQueryOrder";
}

@end
