// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTRespGetRecSchoolClass.h"

@implementation ApolloTRespGetRecSchoolClass

@synthesize JV2_PROP_EX(r,0,vRecSchoolGroups,VOApolloTRecSchoolGroup);

+ (void)initialize
{
    if (self == [ApolloTRespGetRecSchoolClass class]) {
        [ApolloTRecSchoolGroup initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vRecSchoolGroups) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetRecSchoolClass";
}

@end
