// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Bean.jce'
// **********************************************************************

#import "ApolloTReqBeanOperation.h"

@implementation ApolloTReqBeanOperation

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,identity);
@synthesize JV2_PROP_NM(r,2,iRuleId);
@synthesize JV2_PROP_NM(r,3,number);
@synthesize JV2_PROP_NM(r,4,clientType);
@synthesize JV2_PROP_NM(o,5,transformBean);
@synthesize JV2_PROP_NM(o,6,consumeBean);

+ (void)initialize
{
    if (self == [ApolloTReqBeanOperation class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqBeanOperation";
}

@end
