// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTStudent.h"
#import "ApolloTTeacher.h"

@interface ApolloTRespGetClassMember : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vStudents,setVStudents:)) NSArray* JV2_PROP_EX(o,0,vStudents,VOApolloTStudent);
@property (nonatomic, retain, JV2_PROP_GS_V2(vTeachers,setVTeachers:)) NSArray* JV2_PROP_EX(o,1,vTeachers,VOApolloTTeacher);

@end
