// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqCreateOfficialAccount.h"

@implementation ApolloTReqCreateOfficialAccount

@synthesize JV2_PROP_NM(r,0,name);
@synthesize JV2_PROP_NM(r,1,sex);
@synthesize JV2_PROP_NM(r,2,teacherauth);
@synthesize JV2_PROP_NM(r,3,photo);

+ (void)initialize
{
    if (self == [ApolloTReqCreateOfficialAccount class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(photo) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqCreateOfficialAccount";
}

@end
