// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqGetSingleSendedNotice : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(noticeid,setNoticeid:)) JceInt64 JV2_PROP_NM(r,0,noticeid);
@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt64 JV2_PROP_NM(r,1,index);
@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,2,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(clientType,setClientType:)) JceInt32 JV2_PROP_NM(r,3,clientType);

@end
