// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqDelChildFocusUser.h"

@implementation ApolloTReqDelChildFocusUser

@synthesize JV2_PROP_NM(r,0,childid);
@synthesize JV2_PROP_NM(r,1,focusUid);

+ (void)initialize
{
    if (self == [ApolloTReqDelChildFocusUser class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(childid) = DefaultJceString;
        JV2_PROP(focusUid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqDelChildFocusUser";
}

@end
