// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Apollo.jce'
// **********************************************************************

#import "ApolloTReqQueryOnLineUser.h"

@implementation ApolloTReqQueryOnLineUser

@synthesize JV2_PROP_NM(r,0,timestamp);

+ (void)initialize
{
    if (self == [ApolloTReqQueryOnLineUser class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqQueryOnLineUser";
}

@end
