// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneMessageBox.h"

@interface ApolloTRespZoneMessageBox : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(messageBoxs,setMessageBoxs:)) ApolloTZoneMessageBox* JV2_PROP_NM(o,0,messageBoxs);

@end
