// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTNoticeReadTime.h"

@implementation ApolloTNoticeReadTime

@synthesize JV2_PROP_NM(r,0,iNoticeId);
@synthesize JV2_PROP_NM(r,1,readTime);
@synthesize JV2_PROP_NM(r,2,userid);
@synthesize JV2_PROP_NM(r,3,tagid);

+ (void)initialize
{
    if (self == [ApolloTNoticeReadTime class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(userid) = DefaultJceString;
        JV2_PROP(tagid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TNoticeReadTime";
}

@end
