// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTRespGetSendedNotices.h"

@implementation ApolloTRespGetSendedNotices

@synthesize JV2_PROP_EX(r,0,vNotice,VOApolloTNotice);
@synthesize JV2_PROP_NM(r,1,total);

+ (void)initialize
{
    if (self == [ApolloTRespGetSendedNotices class]) {
        [ApolloTNotice initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vNotice) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetSendedNotices";
}

@end
