// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespSendSmsInvitation : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vRegisteredMobilePhones,setVRegisteredMobilePhones:)) NSArray* JV2_PROP_EX(r,0,vRegisteredMobilePhones,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vManyTimesInviteMobilePhones,setVManyTimesInviteMobilePhones:)) NSArray* JV2_PROP_EX(r,1,vManyTimesInviteMobilePhones,VONSString);

@end
