// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Package.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloCLIENT_TYPE_Unknown = 0,
    ApolloCLIENT_TYPE_Android = 1,
    ApolloCLIENT_TYPE_IOS = 2,
    ApolloCLIENT_TYPE_WEB = 3,
    ApolloCLIENT_TYPE_OTHER = 4,
    ApolloCLIENT_TYPE_PHP = 5
};
#define ApolloCLIENT_TYPE NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloCLIENT_TYPEHelper: JceEnumHelper

+ (NSString *)etos:(ApolloCLIENT_TYPE)e;
+ (ApolloCLIENT_TYPE)stoe:(NSString *)s;

@end

#endif
