// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/chat.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloCHAT_TYPE_CHAT_SINGLE = 0,
    ApolloCHAT_TYPE_CHAT_GROUP = 1
};
#define ApolloCHAT_TYPE NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloCHAT_TYPEHelper: JceEnumHelper

+ (NSString *)etos:(ApolloCHAT_TYPE)e;
+ (ApolloCHAT_TYPE)stoe:(NSString *)s;

@end

#endif
