// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqPushZoneMessageBox.h"

@implementation ApolloTReqPushZoneMessageBox

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,messageBox);
@synthesize JV2_PROP_NM(r,2,readLocation);

+ (void)initialize
{
    if (self == [ApolloTReqPushZoneMessageBox class]) {
        [ApolloTZoneMessageBox initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(messageBox) = [ApolloTZoneMessageBox object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqPushZoneMessageBox";
}

@end
