// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTChildSchoolAndClassInfo.h"

@implementation ApolloTChildSchoolAndClassInfo

@synthesize JV2_PROP_NM(r,0,sid);
@synthesize JV2_PROP_NM(r,1,schoolName);
@synthesize JV2_PROP_NM(r,2,cid);
@synthesize JV2_PROP_NM(r,3,cName);

+ (void)initialize
{
    if (self == [ApolloTChildSchoolAndClassInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(schoolName) = DefaultJceString;
        JV2_PROP(cName) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TChildSchoolAndClassInfo";
}

@end
