// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTRespGetInvitedClassFeeCard.h"

@implementation ApolloTRespGetInvitedClassFeeCard

@synthesize JV2_PROP_NM(r,0,money);

+ (void)initialize
{
    if (self == [ApolloTRespGetInvitedClassFeeCard class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetInvitedClassFeeCard";
}

@end
