// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTNoticeText.h"

@implementation ApolloTNoticeText

@synthesize JV2_PROP_NM(r,0,content);
@synthesize JV2_PROP_EX(o,1,vPhotos,VONSString);
@synthesize JV2_PROP_EX(o,2,vVoices,VONSString);
@synthesize JV2_PROP_EX(o,3,vScore,VOApolloTScoreContent);
@synthesize JV2_PROP_NM(o,4,subject);
@synthesize JV2_PROP_NM(o,5,actionUrl);
@synthesize JV2_PROP_NM(o,6,actionText);

+ (void)initialize
{
    if (self == [ApolloTNoticeText class]) {
        [ApolloTScoreContent initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(content) = DefaultJceString;
        JV2_PROP(subject) = DefaultJceString;
        JV2_PROP(actionUrl) = DefaultJceString;
        JV2_PROP(actionText) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TNoticeText";
}

@end
