// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqCreatClass.h"

@implementation ApolloTReqCreatClass

@synthesize JV2_PROP_NM(r,0,name);
@synthesize JV2_PROP_NM(r,1,sid);
@synthesize JV2_PROP_NM(r,2,classtype);
@synthesize JV2_PROP_NM(r,3,grade);
@synthesize JV2_PROP_NM(r,4,phone);
@synthesize JV2_PROP_NM(r,5,mastername);
@synthesize JV2_PROP_NM(r,6,joinverify);

+ (void)initialize
{
    if (self == [ApolloTReqCreatClass class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(phone) = DefaultJceString;
        JV2_PROP(mastername) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqCreatClass";
}

@end
