// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqModifyObjectLocation.h"

@implementation ApolloTReqModifyObjectLocation

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,objectid);
@synthesize JV2_PROP_NM(r,2,Type);
@synthesize JV2_PROP_NM(r,3,LocationType);
@synthesize JV2_PROP_NM(r,4,location);
@synthesize JV2_PROP_NM(r,5,levelId);
@synthesize JV2_PROP_NM(o,6,modifyType);

+ (void)initialize
{
    if (self == [ApolloTReqModifyObjectLocation class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqModifyObjectLocation";
}

@end
