// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTRespJoinClass.h"

@implementation ApolloTRespJoinClass

@synthesize JV2_PROP_NM(r,0,studentId);

+ (void)initialize
{
    if (self == [ApolloTRespJoinClass class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(studentId) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespJoinClass";
}

@end
