// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTStuctClassTeacher : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(subject,setSubject:)) NSString* JV2_PROP_NM(r,1,subject);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt16 JV2_PROP_NM(r,2,type);
@property (nonatomic, assign, JV2_PROP_GS_V2(creationtime,setCreationtime:)) JceInt64 JV2_PROP_NM(r,3,creationtime);

@end
