// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqWeiXiNotifyResult : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(appid,setAppid:)) NSString* JV2_PROP_NM(r,0,appid);
@property (nonatomic, retain, JV2_PROP_GS_V2(mch_id,setMch_id:)) NSString* JV2_PROP_NM(r,1,mch_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(nonce_str,setNonce_str:)) NSString* JV2_PROP_NM(r,2,nonce_str);
@property (nonatomic, retain, JV2_PROP_GS_V2(sign,setSign:)) NSString* JV2_PROP_NM(r,3,sign);
@property (nonatomic, retain, JV2_PROP_GS_V2(result_code,setResult_code:)) NSString* JV2_PROP_NM(r,4,result_code);
@property (nonatomic, retain, JV2_PROP_GS_V2(openid,setOpenid:)) NSString* JV2_PROP_NM(r,5,openid);
@property (nonatomic, retain, JV2_PROP_GS_V2(trade_type,setTrade_type:)) NSString* JV2_PROP_NM(r,6,trade_type);
@property (nonatomic, retain, JV2_PROP_GS_V2(bank_type,setBank_type:)) NSString* JV2_PROP_NM(r,7,bank_type);
@property (nonatomic, retain, JV2_PROP_GS_V2(total_fee,setTotal_fee:)) NSString* JV2_PROP_NM(r,8,total_fee);
@property (nonatomic, retain, JV2_PROP_GS_V2(cash_fee,setCash_fee:)) NSString* JV2_PROP_NM(r,9,cash_fee);
@property (nonatomic, retain, JV2_PROP_GS_V2(transaction_id,setTransaction_id:)) NSString* JV2_PROP_NM(r,10,transaction_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(out_trade_no,setOut_trade_no:)) NSString* JV2_PROP_NM(r,11,out_trade_no);
@property (nonatomic, retain, JV2_PROP_GS_V2(time_end,setTime_end:)) NSString* JV2_PROP_NM(r,12,time_end);

@end
