// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClientProto.jce'
// **********************************************************************

#import "ApolloTMsgRequestEcho.h"

@implementation ApolloTMsgRequestEcho

@synthesize JV2_PROP_NM(r,0,iTime);

+ (void)initialize
{
    if (self == [ApolloTMsgRequestEcho class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TMsgRequestEcho";
}

@end
