// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneMsgContent.h"

@interface ApolloTReqSendZoneMsg : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(senderId,setSenderId:)) NSString* JV2_PROP_NM(r,0,senderId);
@property (nonatomic, retain, JV2_PROP_GS_V2(content,setContent:)) ApolloTZoneMsgContent* JV2_PROP_NM(r,1,content);
@property (nonatomic, retain, JV2_PROP_GS_V2(describe,setDescribe:)) NSString* JV2_PROP_NM(r,2,describe);
@property (nonatomic, assign, JV2_PROP_GS_V2(openStatus,setOpenStatus:)) JceInt32 JV2_PROP_NM(r,3,openStatus);
@property (nonatomic, assign, JV2_PROP_GS_V2(location,setLocation:)) JceInt32 JV2_PROP_NM(r,4,location);
@property (nonatomic, assign, JV2_PROP_GS_V2(publishTime,setPublishTime:)) JceInt64 JV2_PROP_NM(r,5,publishTime);

@end
