// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTReqGetSendedSMS.h"

@implementation ApolloTReqGetSendedSMS

@synthesize JV2_PROP_NM(r,0,index);
@synthesize JV2_PROP_NM(r,1,flag);
@synthesize JV2_PROP_NM(r,2,uid);

+ (void)initialize
{
    if (self == [ApolloTReqGetSendedSMS class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqGetSendedSMS";
}

@end
