// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "ApolloTRespBindClassFeeCard.h"

@implementation ApolloTRespBindClassFeeCard

@synthesize JV2_PROP_NM(r,0,card);

+ (void)initialize
{
    if (self == [ApolloTRespBindClassFeeCard class]) {
        [ApolloTClassFeeCard initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(card) = [ApolloTClassFeeCard object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespBindClassFeeCard";
}

@end
