// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqSendZoneMessasge.h"

@implementation ApolloTReqSendZoneMessasge

@synthesize JV2_PROP_NM(r,0,message);
@synthesize JV2_PROP_NM(r,1,type);
@synthesize JV2_PROP_NM(r,2,userType);
@synthesize JV2_PROP_NM(o,3,region);

+ (void)initialize
{
    if (self == [ApolloTReqSendZoneMessasge class]) {
        [ApolloTZoneMessage initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(message) = [ApolloTZoneMessage object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSendZoneMessasge";
}

@end
