// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/connect.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespAuth : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iRet,setIRet:)) JceInt32 JV2_PROP_NM(r,0,iRet);
@property (nonatomic, retain, JV2_PROP_GS_V2(sMsg,setSMsg:)) NSString* JV2_PROP_NM(r,1,sMsg);
@property (nonatomic, assign, JV2_PROP_GS_V2(iTime,setITime:)) JceInt32 JV2_PROP_NM(r,2,iTime);

@end
