// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqEditWtihdrawWhiteList : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uids,setUids:)) NSArray* JV2_PROP_EX(r,0,uids,VONSString);
@property (nonatomic, assign, JV2_PROP_GS_V2(option,setOption:)) JceInt32 JV2_PROP_NM(r,1,option);

@end
