// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqDailyPaperMessages.h"

@implementation ApolloTReqDailyPaperMessages

@synthesize JV2_PROP_NM(r,0,channelId);
@synthesize JV2_PROP_NM(r,1,flag);
@synthesize JV2_PROP_NM(r,2,index);

+ (void)initialize
{
    if (self == [ApolloTReqDailyPaperMessages class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(channelId) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqDailyPaperMessages";
}

@end
