// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqCommentList.h"

@implementation ApolloTReqCommentList

@synthesize JV2_PROP_NM(r,0,msgId);
@synthesize JV2_PROP_NM(r,1,index);
@synthesize JV2_PROP_NM(r,2,flag);

+ (void)initialize
{
    if (self == [ApolloTReqCommentList class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqCommentList";
}

@end
