// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Apollo.jce'
// **********************************************************************

#import "ApolloTRespQueryOnLineUser.h"

@implementation ApolloTRespQueryOnLineUser

@synthesize JV2_PROP_NM(r,0,totalOnlineUser);
@synthesize JV2_PROP_NM(r,1,realResptime);

+ (void)initialize
{
    if (self == [ApolloTRespQueryOnLineUser class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespQueryOnLineUser";
}

@end
