// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTSameNameChildInClass : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(studentuid,setStudentuid:)) NSString* JV2_PROP_NM(r,0,studentuid);
@property (nonatomic, retain, JV2_PROP_GS_V2(photo,setPhoto:)) NSString* JV2_PROP_NM(r,1,photo);
@property (nonatomic, retain, JV2_PROP_GS_V2(mobilephone,setMobilephone:)) NSString* JV2_PROP_NM(r,2,mobilephone);
@property (nonatomic, retain, JV2_PROP_GS_V2(role,setRole:)) NSString* JV2_PROP_NM(r,3,role);

@end
