// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTClassGroup.h"

@implementation ApolloTClassGroup

@synthesize JV2_PROP_NM(r,0,name);
@synthesize JV2_PROP_EX(r,1,vClasses,VOApolloTClass);
@synthesize JV2_PROP_NM(o,2,childId);

+ (void)initialize
{
    if (self == [ApolloTClassGroup class]) {
        [ApolloTClass initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(vClasses) = DefaultJceArray;
        JV2_PROP(childId) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TClassGroup";
}

@end
