// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/login.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespCommonLoginOut : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(lTime,setLTime:)) JceInt64 JV2_PROP_NM(r,1,lTime);

@end
