// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTTeacherItem.h"

@interface ApolloTImportClassTeacherItem : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,0,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(classMaster,setClassMaster:)) ApolloTTeacherItem* JV2_PROP_NM(r,1,classMaster);
@property (nonatomic, retain, JV2_PROP_GS_V2(vClassTeacher,setVClassTeacher:)) NSArray* JV2_PROP_EX(r,2,vClassTeacher,VOApolloTTeacherItem);

@end
