// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpProto.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespPackage : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(nCMDID,setNCMDID:)) JceInt32 JV2_PROP_NM(r,0,nCMDID);
@property (nonatomic, assign, JV2_PROP_GS_V2(iSequence,setISequence:)) JceInt64 JV2_PROP_NM(r,1,iSequence);
@property (nonatomic, assign, JV2_PROP_GS_V2(iResult,setIResult:)) JceInt32 JV2_PROP_NM(r,2,iResult);
@property (nonatomic, retain, JV2_PROP_GS_V2(sMessage,setSMessage:)) NSString* JV2_PROP_NM(o,3,sMessage);
@property (nonatomic, retain, JV2_PROP_GS_V2(vecData,setVecData:)) NSData* JV2_PROP_NM(o,4,vecData);

@end
