// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloClassFeeCardEventID.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation ApolloClassFeeCardEventIDHelper

+ (NSString *)etos:(ApolloClassFeeCardEventID)e
{
    switch(e){
        case ApolloClassFeeCardEventID_CFC_EVENT_ROLLOUT: return @"ApolloClassFeeCardEventID_CFC_EVENT_ROLLOUT";
        case ApolloClassFeeCardEventID_CFC_EVENT_ROLLBACK: return @"ApolloClassFeeCardEventID_CFC_EVENT_ROLLBACK";
        default: return @"";
    }
}

+ (ApolloClassFeeCardEventID)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"ApolloClassFeeCardEventID_CFC_EVENT_ROLLOUT")) return ApolloClassFeeCardEventID_CFC_EVENT_ROLLOUT;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeCardEventID_CFC_EVENT_ROLLBACK")) return ApolloClassFeeCardEventID_CFC_EVENT_ROLLBACK;
    return NSIntegerMin;
}

@end

#endif
