// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTNoticeMessage.h"

@implementation ApolloTNoticeMessage

@synthesize JV2_PROP_NM(r,0,iNoticeId);
@synthesize JV2_PROP_NM(r,1,sSenderId);
@synthesize JV2_PROP_NM(r,2,sSenderPhoto);
@synthesize JV2_PROP_NM(r,3,sSenderTitle);
@synthesize JV2_PROP_NM(r,4,sReceiverId);
@synthesize JV2_PROP_NM(r,5,targteid);
@synthesize JV2_PROP_NM(r,6,tagidName);
@synthesize JV2_PROP_NM(r,7,targtePhoto);
@synthesize JV2_PROP_NM(r,8,iType);
@synthesize JV2_PROP_NM(r,9,tContent);
@synthesize JV2_PROP_NM(r,10,lSendTime);
@synthesize JV2_PROP_NM(r,11,index);
@synthesize JV2_PROP_NM(o,12,read);
@synthesize JV2_PROP_NM(o,13,evalute);
@synthesize JV2_PROP_NM(o,14,action);
@synthesize JV2_PROP_NM(o,15,teacherauth);

+ (void)initialize
{
    if (self == [ApolloTNoticeMessage class]) {
        [ApolloTNoticeText initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sSenderId) = DefaultJceString;
        JV2_PROP(sSenderPhoto) = DefaultJceString;
        JV2_PROP(sSenderTitle) = DefaultJceString;
        JV2_PROP(sReceiverId) = DefaultJceString;
        JV2_PROP(targteid) = DefaultJceString;
        JV2_PROP(tagidName) = DefaultJceString;
        JV2_PROP(targtePhoto) = DefaultJceString;
        JV2_PROP(tContent) = [ApolloTNoticeText object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TNoticeMessage";
}

@end
