// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/chat.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTChatMessage.h"

@interface ApolloTRespGetChatMessage : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vChatMessages,setVChatMessages:)) NSArray* JV2_PROP_EX(r,0,vChatMessages,VOApolloTChatMessage);
@property (nonatomic, assign, JV2_PROP_GS_V2(unarrive,setUnarrive:)) JceInt32 JV2_PROP_NM(r,1,unarrive);

@end
