// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneComment.h"
#import "ApolloTZoneLikerObject.h"
#import "ApolloTZoneMsg.h"
#import "ApolloTZoneMsgContent.h"

@interface ApolloTRespZoneMsgDetail : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(conent,setConent:)) ApolloTZoneMsgContent* JV2_PROP_NM(r,0,conent);
@property (nonatomic, retain, JV2_PROP_GS_V2(comments,setComments:)) NSArray* JV2_PROP_EX(r,1,comments,VOApolloTZoneComment);
@property (nonatomic, retain, JV2_PROP_GS_V2(likers,setLikers:)) NSArray* JV2_PROP_EX(r,2,likers,VOApolloTZoneLikerObject);
@property (nonatomic, retain, JV2_PROP_GS_V2(msg,setMsg:)) ApolloTZoneMsg* JV2_PROP_NM(o,3,msg);
@property (nonatomic, retain, JV2_PROP_GS_V2(hotComments,setHotComments:)) NSArray* JV2_PROP_EX(o,4,hotComments,VOApolloTZoneComment);

@end
