// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqCreateChild.h"

@implementation ApolloTReqCreateChild

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_NM(r,2,role);
@synthesize JV2_PROP_NM(o,3,photo);
@synthesize JV2_PROP_NM(o,4,sex);
@synthesize JV2_PROP_NM(o,5,birthday);

+ (void)initialize
{
    if (self == [ApolloTReqCreateChild class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(role) = DefaultJceString;
        JV2_PROP(photo) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqCreateChild";
}

@end
