// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Package.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneHotType.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation ApolloTZoneHotTypeHelper

+ (NSString *)etos:(ApolloTZoneHotType)e
{
    switch(e){
        case ApolloTZoneHotType_E_COM: return @"ApolloTZoneHotType_E_COM";
        case ApolloTZoneHotType_E_ADVERT: return @"ApolloTZoneHotType_E_ADVERT";
        case ApolloTZoneHotType_E_Channel: return @"ApolloTZoneHotType_E_Channel";
        default: return @"";
    }
}

+ (ApolloTZoneHotType)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"ApolloTZoneHotType_E_COM")) return ApolloTZoneHotType_E_COM;
    if(isJceEnumStringEqual(s, @"ApolloTZoneHotType_E_ADVERT")) return ApolloTZoneHotType_E_ADVERT;
    if(isJceEnumStringEqual(s, @"ApolloTZoneHotType_E_Channel")) return ApolloTZoneHotType_E_Channel;
    return NSIntegerMin;
}

@end

#endif
