// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Bean.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqBeanOperation : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(identity,setIdentity:)) JceInt32 JV2_PROP_NM(r,1,identity);
@property (nonatomic, assign, JV2_PROP_GS_V2(iRuleId,setIRuleId:)) JceInt32 JV2_PROP_NM(r,2,iRuleId);
@property (nonatomic, assign, JV2_PROP_GS_V2(number,setNumber:)) JceInt32 JV2_PROP_NM(r,3,number);
@property (nonatomic, assign, JV2_PROP_GS_V2(clientType,setClientType:)) JceInt32 JV2_PROP_NM(r,4,clientType);
@property (nonatomic, assign, JV2_PROP_GS_V2(transformBean,setTransformBean:)) JceInt32 JV2_PROP_NM(o,5,transformBean);
@property (nonatomic, assign, JV2_PROP_GS_V2(consumeBean,setConsumeBean:)) JceInt32 JV2_PROP_NM(o,6,consumeBean);

@end
