// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTScoreContent.h"

@implementation ApolloTScoreContent

@synthesize JV2_PROP_NM(r,0,tagid);
@synthesize JV2_PROP_NM(r,1,title);
@synthesize JV2_PROP_NM(r,2,examine);
@synthesize JV2_PROP_NM(r,3,timestamp);
@synthesize JV2_PROP_EX(r,4,vSubjectScore,VOApolloTSubjectScore);
@synthesize JV2_PROP_NM(o,5,cid);

+ (void)initialize
{
    if (self == [ApolloTScoreContent class]) {
        [ApolloTSubjectScore initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(tagid) = DefaultJceString;
        JV2_PROP(title) = DefaultJceString;
        JV2_PROP(examine) = DefaultJceString;
        JV2_PROP(vSubjectScore) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TScoreContent";
}

@end
