// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneSenderObject.h"

@interface ApolloTZoneMessage : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(mid,setMid:)) JceInt64 JV2_PROP_NM(r,0,mid);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt32 JV2_PROP_NM(r,1,type);
@property (nonatomic, assign, JV2_PROP_GS_V2(action,setAction:)) JceInt32 JV2_PROP_NM(r,2,action);
@property (nonatomic, retain, JV2_PROP_GS_V2(msgid,setMsgid:)) NSString* JV2_PROP_NM(r,3,msgid);
@property (nonatomic, retain, JV2_PROP_GS_V2(content,setContent:)) NSString* JV2_PROP_NM(r,4,content);
@property (nonatomic, retain, JV2_PROP_GS_V2(sender,setSender:)) ApolloTZoneSenderObject* JV2_PROP_NM(r,5,sender);
@property (nonatomic, assign, JV2_PROP_GS_V2(sendertime,setSendertime:)) JceInt64 JV2_PROP_NM(o,6,sendertime);
@property (nonatomic, assign, JV2_PROP_GS_V2(iNewArrival,setINewArrival:)) JceInt32 JV2_PROP_NM(o,7,iNewArrival);

@end
