// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloSystemNoticeReceiveObject : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(tagid,setTagid:)) NSString* JV2_PROP_NM(r,1,tagid);
@property (nonatomic, retain, JV2_PROP_GS_V2(tagidName,setTagidName:)) NSString* JV2_PROP_NM(o,2,tagidName);

@end
