// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTSchoolInfo.h"

@implementation ApolloTSchoolInfo

@synthesize JV2_PROP_NM(r,0,sid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_NM(r,2,aid);
@synthesize JV2_PROP_NM(r,3,createtype);
@synthesize JV2_PROP_NM(r,4,smsnum);
@synthesize JV2_PROP_NM(r,5,schoolcode);
@synthesize JV2_PROP_NM(r,6,isauth);
@synthesize JV2_PROP_NM(r,7,buysms);
@synthesize JV2_PROP_NM(r,8,pingyin);

+ (void)initialize
{
    if (self == [ApolloTSchoolInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(schoolcode) = DefaultJceString;
        JV2_PROP(pingyin) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TSchoolInfo";
}

@end
