// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Upgrade.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTVersionInfo : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iClientType,setIClientType:)) JceInt32 JV2_PROP_NM(r,0,iClientType);
@property (nonatomic, retain, JV2_PROP_GS_V2(strAppVer,setStrAppVer:)) NSString* JV2_PROP_NM(r,1,strAppVer);
@property (nonatomic, retain, JV2_PROP_GS_V2(strForceVer,setStrForceVer:)) NSString* JV2_PROP_NM(r,2,strForceVer);
@property (nonatomic, retain, JV2_PROP_GS_V2(strPromptVer,setStrPromptVer:)) NSString* JV2_PROP_NM(r,3,strPromptVer);
@property (nonatomic, retain, JV2_PROP_GS_V2(strDownUrl,setStrDownUrl:)) NSString* JV2_PROP_NM(o,4,strDownUrl);
@property (nonatomic, retain, JV2_PROP_GS_V2(strUpgradeMsg,setStrUpgradeMsg:)) NSString* JV2_PROP_NM(o,5,strUpgradeMsg);
@property (nonatomic, assign, JV2_PROP_GS_V2(iSort,setISort:)) JceInt32 JV2_PROP_NM(o,6,iSort);

@end
