// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqTotalMoneyAndHead : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(ruleid,setRuleid:)) NSString* JV2_PROP_NM(r,0,ruleid);

@end
