// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTChildFocusUser.h"

@interface ApolloTRespGetChildFocusUser : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vFocusUseres,setVFocusUseres:)) NSArray* JV2_PROP_EX(r,0,vFocusUseres,VOApolloTChildFocusUser);
@property (nonatomic, assign, JV2_PROP_GS_V2(maxCount,setMaxCount:)) JceInt32 JV2_PROP_NM(r,1,maxCount);

@end
