// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTReqJoinClassFeeCardActivity.h"

@interface ApolloTReqBatchUidJoinActive : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vecReqJoinActive,setVecReqJoinActive:)) NSArray* JV2_PROP_EX(r,0,vecReqJoinActive,VOApolloTReqJoinClassFeeCardActivity);

@end
