// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloCLASS_FEE_CARD_RULE_TYPE.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation ApolloCLASS_FEE_CARD_RULE_TYPEHelper

+ (NSString *)etos:(ApolloCLASS_FEE_CARD_RULE_TYPE)e
{
    switch(e){
        case ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_UNKNOW: return @"ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_UNKNOW";
        case ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_RADOM: return @"ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_RADOM";
        case ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_FIXED: return @"ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_FIXED";
        default: return @"";
    }
}

+ (ApolloCLASS_FEE_CARD_RULE_TYPE)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_UNKNOW")) return ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_UNKNOW;
    if(isJceEnumStringEqual(s, @"ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_RADOM")) return ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_RADOM;
    if(isJceEnumStringEqual(s, @"ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_FIXED")) return ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_FIXED;
    return NSIntegerMin;
}

@end

#endif
