// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneMsg.h"
#import "ApolloTZoneMsgContent.h"

@interface ApolloTReqUpdateZoneMsg : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(msg,setMsg:)) ApolloTZoneMsg* JV2_PROP_NM(r,1,msg);
@property (nonatomic, retain, JV2_PROP_GS_V2(content,setContent:)) ApolloTZoneMsgContent* JV2_PROP_NM(r,2,content);

@end
