// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/login.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqLoginRegister : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(mobile,setMobile:)) NSString* JV2_PROP_NM(r,0,mobile);
@property (nonatomic, retain, JV2_PROP_GS_V2(verifycode,setVerifycode:)) NSString* JV2_PROP_NM(r,1,verifycode);
@property (nonatomic, retain, JV2_PROP_GS_V2(pwd,setPwd:)) NSString* JV2_PROP_NM(r,2,pwd);
@property (nonatomic, retain, JV2_PROP_GS_V2(username,setUsername:)) NSString* JV2_PROP_NM(r,3,username);
@property (nonatomic, retain, JV2_PROP_GS_V2(sDeviceID,setSDeviceID:)) NSString* JV2_PROP_NM(r,4,sDeviceID);
@property (nonatomic, retain, JV2_PROP_GS_V2(apnsToken,setApnsToken:)) NSString* JV2_PROP_NM(o,5,apnsToken);
@property (nonatomic, retain, JV2_PROP_GS_V2(invitemobile,setInvitemobile:)) NSString* JV2_PROP_NM(o,6,invitemobile);
@property (nonatomic, retain, JV2_PROP_GS_V2(phonetype,setPhonetype:)) NSString* JV2_PROP_NM(o,7,phonetype);

@end
