// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqSetChildInfo.h"

@implementation ApolloTReqSetChildInfo

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,flag);
@synthesize JV2_PROP_NM(r,2,photo);
@synthesize JV2_PROP_NM(r,3,name);
@synthesize JV2_PROP_NM(r,4,sex);
@synthesize JV2_PROP_NM(r,5,role);
@synthesize JV2_PROP_NM(r,6,birthday);

+ (void)initialize
{
    if (self == [ApolloTReqSetChildInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(photo) = DefaultJceString;
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(role) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSetChildInfo";
}

@end
