// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTStudent.h"

@interface ApolloTUserInfoForSendSysNotice : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(masterName,setMasterName:)) NSString* JV2_PROP_NM(r,0,masterName);
@property (nonatomic, retain, JV2_PROP_GS_V2(masterIcon,setMasterIcon:)) NSString* JV2_PROP_NM(r,1,masterIcon);
@property (nonatomic, retain, JV2_PROP_GS_V2(userName,setUserName:)) NSString* JV2_PROP_NM(r,2,userName);
@property (nonatomic, retain, JV2_PROP_GS_V2(userIcon,setUserIcon:)) NSString* JV2_PROP_NM(r,3,userIcon);
@property (nonatomic, retain, JV2_PROP_GS_V2(student,setStudent:)) ApolloTStudent* JV2_PROP_NM(r,4,student);
@property (nonatomic, retain, JV2_PROP_GS_V2(masterUid,setMasterUid:)) NSString* JV2_PROP_NM(r,5,masterUid);

@end
