// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTRespCommentList.h"

@implementation ApolloTRespCommentList

@synthesize JV2_PROP_EX(r,0,vComments,VOApolloTZoneComment);
@synthesize JV2_PROP_EX(o,1,vhotComments,VOApolloTZoneComment);
@synthesize JV2_PROP_NM(o,2,commentNum);
@synthesize JV2_PROP_NM(o,3,likeNum);
@synthesize JV2_PROP_EX(o,4,likers,VOApolloTZoneLikerObject);

+ (void)initialize
{
    if (self == [ApolloTRespCommentList class]) {
        [ApolloTZoneComment initialize];
        [ApolloTZoneLikerObject initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vComments) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespCommentList";
}

@end
