// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTRespGetSendedSMS.h"

@implementation ApolloTRespGetSendedSMS

@synthesize JV2_PROP_EX(r,0,vSMSMsg,VOApolloTSMSMsg);
@synthesize JV2_PROP_NM(r,1,total);

+ (void)initialize
{
    if (self == [ApolloTRespGetSendedSMS class]) {
        [ApolloTSMSMsg initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vSMSMsg) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetSendedSMS";
}

@end
