// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Upgrade.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqUpgrade : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iClientType,setIClientType:)) JceInt32 JV2_PROP_NM(r,0,iClientType);
@property (nonatomic, retain, JV2_PROP_GS_V2(strAppVer,setStrAppVer:)) NSString* JV2_PROP_NM(r,1,strAppVer);
@property (nonatomic, retain, JV2_PROP_GS_V2(sUid,setSUid:)) NSString* JV2_PROP_NM(r,2,sUid);

@end
