// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqClassFeeCardBillDetail : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(lOrderNum,setLOrderNum:)) JceInt64 JV2_PROP_NM(r,1,lOrderNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(iNum,setINum:)) JceInt32 JV2_PROP_NM(r,2,iNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(flag,setFlag:)) JceInt32 JV2_PROP_NM(r,3,flag);

@end
