// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClientProto.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTMsgTest : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iSec,setISec:)) JceInt32 JV2_PROP_NM(r,0,iSec);
@property (nonatomic, assign, JV2_PROP_GS_V2(iUSec,setIUSec:)) JceInt32 JV2_PROP_NM(r,1,iUSec);

@end
