// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqUpdateZoneAdv.h"

@implementation ApolloTReqUpdateZoneAdv

@synthesize JV2_PROP_NM(r,0,adv);

+ (void)initialize
{
    if (self == [ApolloTReqUpdateZoneAdv class]) {
        [ApolloTZoneAdv initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(adv) = [ApolloTZoneAdv object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqUpdateZoneAdv";
}

@end
