// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTSameNameChildInClass.h"

@implementation ApolloTSameNameChildInClass

@synthesize JV2_PROP_NM(r,0,studentuid);
@synthesize JV2_PROP_NM(r,1,photo);
@synthesize JV2_PROP_NM(r,2,mobilephone);
@synthesize JV2_PROP_NM(r,3,role);

+ (void)initialize
{
    if (self == [ApolloTSameNameChildInClass class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(studentuid) = DefaultJceString;
        JV2_PROP(photo) = DefaultJceString;
        JV2_PROP(mobilephone) = DefaultJceString;
        JV2_PROP(role) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TSameNameChildInClass";
}

@end
