// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTSchoolTypeInfo.h"

@implementation ApolloTSchoolTypeInfo

@synthesize JV2_PROP_NM(r,0,stid);
@synthesize JV2_PROP_NM(r,1,name);

+ (void)initialize
{
    if (self == [ApolloTSchoolTypeInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TSchoolTypeInfo";
}

@end
