// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTMyChild.h"

@interface ApolloTRespGetParentChildren : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vMyChildren,setVMyChildren:)) NSArray* JV2_PROP_EX(r,0,vMyChildren,VOApolloTMyChild);
@property (nonatomic, retain, JV2_PROP_GS_V2(vFocusChildren,setVFocusChildren:)) NSArray* JV2_PROP_EX(r,1,vFocusChildren,VOApolloTMyChild);

@end
