// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTNoticeMessageBox.h"

@interface ApolloTRespGetNoticeboxs : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vNoticeboxs,setVNoticeboxs:)) NSArray* JV2_PROP_EX(r,0,vNoticeboxs,VOApolloTNoticeMessageBox);

@end
