// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_UNKNOW = 0,
    ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_RADOM = 1,
    ApolloCLASS_FEE_CARD_RULE_TYPE_CLASS_FEE_CARD_RULE_FIXED = 2
};
#define ApolloCLASS_FEE_CARD_RULE_TYPE NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloCLASS_FEE_CARD_RULE_TYPEHelper: JceEnumHelper

+ (NSString *)etos:(ApolloCLASS_FEE_CARD_RULE_TYPE)e;
+ (ApolloCLASS_FEE_CARD_RULE_TYPE)stoe:(NSString *)s;

@end

#endif
