// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/audit.jce'
// **********************************************************************

#import "ApolloTRespSendAuditRecord.h"

@implementation ApolloTRespSendAuditRecord

@synthesize JV2_PROP_NM(r,0,result);
@synthesize JV2_PROP_NM(o,1,msg);

+ (void)initialize
{
    if (self == [ApolloTRespSendAuditRecord class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(msg) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespSendAuditRecord";
}

@end
