// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "ApolloTReqCardAmountList.h"

@implementation ApolloTReqCardAmountList

@synthesize JV2_PROP_EX(r,0,uids,VONSString);

+ (void)initialize
{
    if (self == [ApolloTReqCardAmountList class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uids) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqCardAmountList";
}

@end
