// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTRespGetTUser.h"

@implementation ApolloTRespGetTUser

@synthesize JV2_PROP_NM(r,0,user);
@synthesize JV2_PROP_EX(o,1,vChildrenMain,VOApolloTChild);
@synthesize JV2_PROP_EX(o,2,vChildrenForcus,VOApolloTChild);
@synthesize JV2_PROP_NM(o,3,isRelatedClass);
@synthesize JV2_PROP_NM(o,4,timestamp);
@synthesize JV2_PROP_NM(o,5,banban);
@synthesize JV2_PROP_EX(o,6,vThirdAccounts,VOApolloTThirdAccount);
@synthesize JV2_PROP_NM(o,7,canSetBanBanNo);
@synthesize JV2_PROP_NM(o,8,userdesc);
@synthesize JV2_PROP_EX(o,9,vLabels,VOApolloTUserLabel);

+ (void)initialize
{
    if (self == [ApolloTRespGetTUser class]) {
        [ApolloTChild initialize];
        [ApolloTThirdAccount initialize];
        [ApolloTUser initialize];
        [ApolloTUserLabel initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(user) = [ApolloTUser object];
        JV2_PROP(banban) = DefaultJceString;
        JV2_PROP(userdesc) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetTUser";
}

@end
