// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTRespUpdateZoneAdv.h"

@implementation ApolloTRespUpdateZoneAdv

@synthesize JV2_PROP_NM(r,0,aid);

+ (void)initialize
{
    if (self == [ApolloTRespUpdateZoneAdv class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespUpdateZoneAdv";
}

@end
