// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/chat.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloCHAT_TYPE.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation ApolloCHAT_TYPEHelper

+ (NSString *)etos:(ApolloCHAT_TYPE)e
{
    switch(e){
        case ApolloCHAT_TYPE_CHAT_SINGLE: return @"ApolloCHAT_TYPE_CHAT_SINGLE";
        case ApolloCHAT_TYPE_CHAT_GROUP: return @"ApolloCHAT_TYPE_CHAT_GROUP";
        default: return @"";
    }
}

+ (ApolloCHAT_TYPE)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"ApolloCHAT_TYPE_CHAT_SINGLE")) return ApolloCHAT_TYPE_CHAT_SINGLE;
    if(isJceEnumStringEqual(s, @"ApolloCHAT_TYPE_CHAT_GROUP")) return ApolloCHAT_TYPE_CHAT_GROUP;
    return NSIntegerMin;
}

@end

#endif
