// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloClassFeeCardEventID_CFC_EVENT_ROLLOUT = 4,
    ApolloClassFeeCardEventID_CFC_EVENT_ROLLBACK = 5
};
#define ApolloClassFeeCardEventID NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloClassFeeCardEventIDHelper: JceEnumHelper

+ (NSString *)etos:(ApolloClassFeeCardEventID)e;
+ (ApolloClassFeeCardEventID)stoe:(NSString *)s;

@end

#endif
