// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespGetQiniuUpToken : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(token,setToken:)) NSString* JV2_PROP_NM(r,0,token);
@property (nonatomic, retain, JV2_PROP_GS_V2(url,setUrl:)) NSString* JV2_PROP_NM(r,1,url);

@end
