// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/audit.jce'
// **********************************************************************

#import "ApolloTAuditRecord.h"

@implementation ApolloTAuditRecord

@synthesize JV2_PROP_NM(r,0,id);
@synthesize JV2_PROP_NM(r,1,uid);
@synthesize JV2_PROP_NM(o,2,childName);
@synthesize JV2_PROP_NM(r,3,userName);
@synthesize JV2_PROP_NM(r,4,phone);
@synthesize JV2_PROP_NM(r,5,photo);
@synthesize JV2_PROP_NM(r,6,content);
@synthesize JV2_PROP_NM(r,7,cid);
@synthesize JV2_PROP_NM(r,8,cidName);
@synthesize JV2_PROP_NM(r,9,createTime);
@synthesize JV2_PROP_NM(r,10,status);
@synthesize JV2_PROP_NM(r,11,index);
@synthesize JV2_PROP_NM(r,12,subject);
@synthesize JV2_PROP_NM(o,13,auditor);
@synthesize JV2_PROP_NM(o,14,auditTime);
@synthesize JV2_PROP_NM(o,15,relation);
@synthesize JV2_PROP_NM(o,16,type);
@synthesize JV2_PROP_NM(o,17,clientType);
@synthesize JV2_PROP_NM(o,18,studentId);

+ (void)initialize
{
    if (self == [ApolloTAuditRecord class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(id) = DefaultJceString;
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(childName) = DefaultJceString;
        JV2_PROP(userName) = DefaultJceString;
        JV2_PROP(phone) = DefaultJceString;
        JV2_PROP(photo) = DefaultJceString;
        JV2_PROP(content) = DefaultJceString;
        JV2_PROP(cidName) = DefaultJceString;
        JV2_PROP(subject) = DefaultJceString;
        JV2_PROP(auditor) = DefaultJceString;
        JV2_PROP(auditTime) = DefaultJceString;
        JV2_PROP(relation) = DefaultJceString;
        JV2_PROP(studentId) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TAuditRecord";
}

@end
