// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloCLIENT_TYPE.h"
#import "ApolloESystemNoticeType.h"
#import "ApolloSystemNoticeReceiveObject.h"

@interface ApolloTReqSendSystemNotice : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(childId,setChildId:)) NSString* JV2_PROP_NM(o,1,childId);
@property (nonatomic, retain, JV2_PROP_GS_V2(childName,setChildName:)) NSString* JV2_PROP_NM(o,2,childName);
@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(r,3,cid);
@property (nonatomic, retain, JV2_PROP_GS_V2(cidName,setCidName:)) NSString* JV2_PROP_NM(r,4,cidName);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) ApolloESystemNoticeType JV2_PROP_NM(r,5,type);
@property (nonatomic, retain, JV2_PROP_GS_V2(senderId,setSenderId:)) NSString* JV2_PROP_NM(r,6,senderId);
@property (nonatomic, retain, JV2_PROP_GS_V2(senderIdName,setSenderIdName:)) NSString* JV2_PROP_NM(r,7,senderIdName);
@property (nonatomic, retain, JV2_PROP_GS_V2(senderPhoto,setSenderPhoto:)) NSString* JV2_PROP_NM(r,8,senderPhoto);
@property (nonatomic, assign, JV2_PROP_GS_V2(nPlatform,setNPlatform:)) ApolloCLIENT_TYPE JV2_PROP_NM(r,9,nPlatform);
@property (nonatomic, retain, JV2_PROP_GS_V2(vObject,setVObject:)) NSArray* JV2_PROP_EX(o,10,vObject,VOApolloSystemNoticeReceiveObject);
@property (nonatomic, retain, JV2_PROP_GS_V2(subject,setSubject:)) NSString* JV2_PROP_NM(o,11,subject);

@end
