// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTImportClassTeacherItem.h"

@implementation ApolloTImportClassTeacherItem

@synthesize JV2_PROP_NM(r,0,name);
@synthesize JV2_PROP_NM(r,1,classMaster);
@synthesize JV2_PROP_EX(r,2,vClassTeacher,VOApolloTTeacherItem);

+ (void)initialize
{
    if (self == [ApolloTImportClassTeacherItem class]) {
        [ApolloTTeacherItem initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(classMaster) = [ApolloTTeacherItem object];
        JV2_PROP(vClassTeacher) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TImportClassTeacherItem";
}

@end
