// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTStructStudentGuardian.h"

@implementation ApolloTStructStudentGuardian

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,role);
@synthesize JV2_PROP_NM(r,2,main);

+ (void)initialize
{
    if (self == [ApolloTStructStudentGuardian class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(role) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TStructStudentGuardian";
}

@end
