// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTReqGetNoticeboxs.h"

@implementation ApolloTReqGetNoticeboxs

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_EX(r,1,vChild,VONSString);
@synthesize JV2_PROP_NM(o,2,flag);

+ (void)initialize
{
    if (self == [ApolloTReqGetNoticeboxs class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(vChild) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqGetNoticeboxs";
}

@end
