// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTRespZoneMessageBox.h"

@implementation ApolloTRespZoneMessageBox

@synthesize JV2_PROP_NM(o,0,messageBoxs);

+ (void)initialize
{
    if (self == [ApolloTRespZoneMessageBox class]) {
        [ApolloTZoneMessageBox initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespZoneMessageBox";
}

@end
