// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Package.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloSHARE_SOURCE_Wechat = 1,
    ApolloSHARE_SOURCE_Friendster = 2,
    ApolloSHARE_SOURCE_QQ = 3,
    ApolloSHARE_SOURCE_Weibo = 4,
    ApolloSHARE_SOURCE_QQzone = 5,
    ApolloSHARE_SOURCE_TencentWeibo = 6
};
#define ApolloSHARE_SOURCE NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloSHARE_SOURCEHelper: JceEnumHelper

+ (NSString *)etos:(ApolloSHARE_SOURCE)e;
+ (ApolloSHARE_SOURCE)stoe:(NSString *)s;

@end

#endif
