// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqCreateClass.h"

@implementation ApolloTReqCreateClass

@synthesize JV2_PROP_NM(r,0,name);
@synthesize JV2_PROP_NM(o,1,sid);
@synthesize JV2_PROP_NM(o,2,grade);

+ (void)initialize
{
    if (self == [ApolloTReqCreateClass class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqCreateClass";
}

@end
