// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTRespGetChildFocusUser.h"

@implementation ApolloTRespGetChildFocusUser

@synthesize JV2_PROP_EX(r,0,vFocusUseres,VOApolloTChildFocusUser);
@synthesize JV2_PROP_NM(r,1,maxCount);

+ (void)initialize
{
    if (self == [ApolloTRespGetChildFocusUser class]) {
        [ApolloTChildFocusUser initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vFocusUseres) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetChildFocusUser";
}

@end
