// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "ApolloTReqIncome.h"

@implementation ApolloTReqIncome

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,strName);
@synthesize JV2_PROP_NM(r,2,cid);
@synthesize JV2_PROP_NM(r,3,sEventID);
@synthesize JV2_PROP_NM(o,4,iAdNo);
@synthesize JV2_PROP_NM(o,5,iAdID);
@synthesize JV2_PROP_NM(o,6,money);
@synthesize JV2_PROP_NM(o,7,remark);

+ (void)initialize
{
    if (self == [ApolloTReqIncome class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(strName) = DefaultJceString;
        JV2_PROP(remark) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqIncome";
}

@end
