// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTRespChildTestJoinClass.h"

@implementation ApolloTRespChildTestJoinClass

@synthesize JV2_PROP_EX(r,0,vSameNameStudent,VOApolloTSameNameChildInClass);

+ (void)initialize
{
    if (self == [ApolloTRespChildTestJoinClass class]) {
        [ApolloTSameNameChildInClass initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vSameNameStudent) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespChildTestJoinClass";
}

@end
