// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Adapte.jce'
// **********************************************************************

#import "ApolloTRespWebSmsInvitation.h"

@implementation ApolloTRespWebSmsInvitation

@synthesize JV2_PROP_NM(r,0,count);

+ (void)initialize
{
    if (self == [ApolloTRespWebSmsInvitation class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespWebSmsInvitation";
}

@end
