// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "ApolloTRespClassFeeInfo.h"

@implementation ApolloTRespClassFeeInfo

@synthesize JV2_PROP_EX(r,0,vFee,VOApolloTClassFee);

+ (void)initialize
{
    if (self == [ApolloTRespClassFeeInfo class]) {
        [ApolloTClassFee initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vFee) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespClassFeeInfo";
}

@end
