// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqOmsBatchResetPwd.h"

@implementation ApolloTReqOmsBatchResetPwd

@synthesize JV2_PROP_EX(r,0,vUid,VONSString);

+ (void)initialize
{
    if (self == [ApolloTReqOmsBatchResetPwd class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vUid) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqOmsBatchResetPwd";
}

@end
