// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTNoticeMessage.h"

@interface ApolloTRespGetNoticeMsg : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vNoticeMsg,setVNoticeMsg:)) NSArray* JV2_PROP_EX(r,0,vNoticeMsg,VOApolloTNoticeMessage);
@property (nonatomic, assign, JV2_PROP_GS_V2(count,setCount:)) JceInt32 JV2_PROP_NM(r,1,count);
@property (nonatomic, assign, JV2_PROP_GS_V2(total,setTotal:)) JceInt32 JV2_PROP_NM(r,2,total);

@end
