// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTScoreContent.h"

@interface ApolloTNoticeText : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(content,setContent:)) NSString* JV2_PROP_NM(r,0,content);
@property (nonatomic, retain, JV2_PROP_GS_V2(vPhotos,setVPhotos:)) NSArray* JV2_PROP_EX(o,1,vPhotos,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vVoices,setVVoices:)) NSArray* JV2_PROP_EX(o,2,vVoices,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(vScore,setVScore:)) NSArray* JV2_PROP_EX(o,3,vScore,VOApolloTScoreContent);
@property (nonatomic, retain, JV2_PROP_GS_V2(subject,setSubject:)) NSString* JV2_PROP_NM(o,4,subject);
@property (nonatomic, retain, JV2_PROP_GS_V2(actionUrl,setActionUrl:)) NSString* JV2_PROP_NM(o,5,actionUrl);
@property (nonatomic, retain, JV2_PROP_GS_V2(actionText,setActionText:)) NSString* JV2_PROP_NM(o,6,actionText);

@end
