// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTRespDeviceActivated.h"

@implementation ApolloTRespDeviceActivated

@synthesize JV2_PROP_NM(r,0,iResult);

+ (void)initialize
{
    if (self == [ApolloTRespDeviceActivated class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespDeviceActivated";
}

@end
