// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespUpdateZoneStatus : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(result,setResult:)) JceInt32 JV2_PROP_NM(r,0,result);
@property (nonatomic, retain, JV2_PROP_GS_V2(msg,setMsg:)) NSString* JV2_PROP_NM(r,1,msg);

@end
