// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "ApolloTRespClassFeeCardBillDetail.h"

@implementation ApolloTRespClassFeeCardBillDetail

@synthesize JV2_PROP_EX(r,0,vLog,VOApolloTClassFeeCardRolloutLog);

+ (void)initialize
{
    if (self == [ApolloTRespClassFeeCardBillDetail class]) {
        [ApolloTClassFeeCardRolloutLog initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vLog) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespClassFeeCardBillDetail";
}

@end
