// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/audit.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloEClassTrendsType.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation ApolloEClassTrendsTypeHelper

+ (NSString *)etos:(ApolloEClassTrendsType)e
{
    switch(e){
        case ApolloEClassTrendsType_ECTT_ALL: return @"ApolloEClassTrendsType_ECTT_ALL";
        case ApolloEClassTrendsType_ECTT_PARTRIARCH_JOIN: return @"ApolloEClassTrendsType_ECTT_PARTRIARCH_JOIN";
        case ApolloEClassTrendsType_ECTT_TEACHER_JOIN: return @"ApolloEClassTrendsType_ECTT_TEACHER_JOIN";
        default: return @"";
    }
}

+ (ApolloEClassTrendsType)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"ApolloEClassTrendsType_ECTT_ALL")) return ApolloEClassTrendsType_ECTT_ALL;
    if(isJceEnumStringEqual(s, @"ApolloEClassTrendsType_ECTT_PARTRIARCH_JOIN")) return ApolloEClassTrendsType_ECTT_PARTRIARCH_JOIN;
    if(isJceEnumStringEqual(s, @"ApolloEClassTrendsType_ECTT_TEACHER_JOIN")) return ApolloEClassTrendsType_ECTT_TEACHER_JOIN;
    return NSIntegerMin;
}

@end

#endif
