// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/connect.jce'
// **********************************************************************

#import "ApolloTNotifyOffline.h"

@implementation ApolloTNotifyOffline

@synthesize JV2_PROP_NM(r,0,iRet);
@synthesize JV2_PROP_NM(r,1,lTime);
@synthesize JV2_PROP_NM(r,2,sMsg);

+ (void)initialize
{
    if (self == [ApolloTNotifyOffline class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sMsg) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TNotifyOffline";
}

@end
