// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/chat.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTChatMessageBox.h"

@interface ApolloTRespGetChatMessageBoxs : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vMessageboxs,setVMessageboxs:)) NSArray* JV2_PROP_EX(r,0,vMessageboxs,VOApolloTChatMessageBox);

@end
