// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqUpdateZone.h"

@implementation ApolloTReqUpdateZone

@synthesize JV2_PROP_NM(r,0,zone);

+ (void)initialize
{
    if (self == [ApolloTReqUpdateZone class]) {
        [ApolloTZoneObject initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(zone) = [ApolloTZoneObject object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqUpdateZone";
}

@end
