// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTSMSMsg.h"

@implementation ApolloTSMSMsg

@synthesize JV2_PROP_NM(r,0,smsid);
@synthesize JV2_PROP_NM(r,1,sSenderId);
@synthesize JV2_PROP_NM(r,2,sSenderPhoto);
@synthesize JV2_PROP_NM(r,3,sSenderTitle);
@synthesize JV2_PROP_EX(r,4,vReceiver,VOApolloTReceiverObject);
@synthesize JV2_PROP_NM(r,5,receiverTitle);
@synthesize JV2_PROP_NM(r,6,iType);
@synthesize JV2_PROP_NM(r,7,content);
@synthesize JV2_PROP_NM(r,8,lSendTime);
@synthesize JV2_PROP_NM(r,9,nPlatform);
@synthesize JV2_PROP_NM(o,10,index);

+ (void)initialize
{
    if (self == [ApolloTSMSMsg class]) {
        [ApolloTReceiverObject initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sSenderId) = DefaultJceString;
        JV2_PROP(sSenderPhoto) = DefaultJceString;
        JV2_PROP(sSenderTitle) = DefaultJceString;
        JV2_PROP(vReceiver) = DefaultJceArray;
        JV2_PROP(receiverTitle) = DefaultJceString;
        JV2_PROP(content) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TSMSMsg";
}

@end
