// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTZoneLikerListUser.h"

@implementation ApolloTZoneLikerListUser

@synthesize JV2_PROP_NM(o,0,index);
@synthesize JV2_PROP_NM(r,1,userObj);

+ (void)initialize
{
    if (self == [ApolloTZoneLikerListUser class]) {
        [ApolloTZoneLikerObject initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(userObj) = [ApolloTZoneLikerObject object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TZoneLikerListUser";
}

@end
