// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqOmsCreateSchool.h"

@implementation ApolloTReqOmsCreateSchool

@synthesize JV2_PROP_NM(r,0,name);
@synthesize JV2_PROP_NM(r,1,aid);
@synthesize JV2_PROP_NM(r,2,stid);
@synthesize JV2_PROP_NM(r,3,isjoin);

+ (void)initialize
{
    if (self == [ApolloTReqOmsCreateSchool class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(stid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqOmsCreateSchool";
}

@end
