// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqSetStudentNumber : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(studentUid,setStudentUid:)) NSString* JV2_PROP_NM(r,0,studentUid);
@property (nonatomic, retain, JV2_PROP_GS_V2(studentNumber,setStudentNumber:)) NSString* JV2_PROP_NM(r,1,studentNumber);

@end
