// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/login.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqInstallStatistics : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(version,setVersion:)) NSString* JV2_PROP_NM(r,0,version);
@property (nonatomic, retain, JV2_PROP_GS_V2(device,setDevice:)) NSString* JV2_PROP_NM(r,1,device);
@property (nonatomic, retain, JV2_PROP_GS_V2(deviceId,setDeviceId:)) NSString* JV2_PROP_NM(r,2,deviceId);

@end
