// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTTeacherInfo.h"

@implementation ApolloTTeacherInfo

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_NM(o,2,photo);
@synthesize JV2_PROP_NM(o,3,type);
@synthesize JV2_PROP_NM(o,4,sex);
@synthesize JV2_PROP_NM(o,5,mobilePhone);
@synthesize JV2_PROP_NM(o,6,subject);
@synthesize JV2_PROP_NM(o,7,joinTime);
@synthesize JV2_PROP_NM(o,8,icon);
@synthesize JV2_PROP_NM(o,9,teacherauth);
@synthesize JV2_PROP_NM(o,10,loginstatus);
@synthesize JV2_PROP_NM(o,11,readTime);

+ (void)initialize
{
    if (self == [ApolloTTeacherInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(photo) = DefaultJceString;
        JV2_PROP(mobilePhone) = DefaultJceString;
        JV2_PROP(subject) = DefaultJceString;
        JV2_PROP(joinTime) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TTeacherInfo";
}

@end
