// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqFocusInChild.h"

@implementation ApolloTReqFocusInChild

@synthesize JV2_PROP_NM(r,0,childid);
@synthesize JV2_PROP_NM(r,1,role);

+ (void)initialize
{
    if (self == [ApolloTReqFocusInChild class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(childid) = DefaultJceString;
        JV2_PROP(role) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqFocusInChild";
}

@end
