// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/connect.jce'
// **********************************************************************

#import "ApolloTNotifyUpdateUserBase.h"

@implementation ApolloTNotifyUpdateUserBase

@synthesize JV2_PROP_NM(r,0,flag);
@synthesize JV2_PROP_NM(o,1,userbase);

+ (void)initialize
{
    if (self == [ApolloTNotifyUpdateUserBase class]) {
        [ApolloTUserBase initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TNotifyUpdateUserBase";
}

@end
