// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/connect.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqAuth : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sVer,setSVer:)) NSString* JV2_PROP_NM(r,0,sVer);
@property (nonatomic, assign, JV2_PROP_GS_V2(nClientType,setNClientType:)) JceInt16 JV2_PROP_NM(r,1,nClientType);
@property (nonatomic, retain, JV2_PROP_GS_V2(sDeviceID,setSDeviceID:)) NSString* JV2_PROP_NM(r,2,sDeviceID);
@property (nonatomic, retain, JV2_PROP_GS_V2(sessionCode,setSessionCode:)) NSString* JV2_PROP_NM(r,3,sessionCode);
@property (nonatomic, assign, JV2_PROP_GS_V2(timestamp,setTimestamp:)) JceInt64 JV2_PROP_NM(o,4,timestamp);
@property (nonatomic, retain, JV2_PROP_GS_V2(apnsToken,setApnsToken:)) NSString* JV2_PROP_NM(o,5,apnsToken);

@end
