// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTRespSendComment.h"

@implementation ApolloTRespSendComment

@synthesize JV2_PROP_NM(r,0,commentId);
@synthesize JV2_PROP_NM(o,1,index);

+ (void)initialize
{
    if (self == [ApolloTRespSendComment class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespSendComment";
}

@end
