// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTZonePictureText.h"

@implementation ApolloTZonePictureText

@synthesize JV2_PROP_NM(o,0,text);
@synthesize JV2_PROP_NM(o,1,picture);
@synthesize JV2_PROP_NM(o,2,video);

+ (void)initialize
{
    if (self == [ApolloTZonePictureText class]) {
        [ApolloTZonePicture initialize];
        [ApolloTZoneVideo initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(text) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TZonePictureText";
}

@end
