// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Upgrade.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTResponseUpgrade : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(sUpgradeType,setSUpgradeType:)) JceInt16 JV2_PROP_NM(r,0,sUpgradeType);
@property (nonatomic, retain, JV2_PROP_GS_V2(strAppVer,setStrAppVer:)) NSString* JV2_PROP_NM(r,1,strAppVer);
@property (nonatomic, retain, JV2_PROP_GS_V2(strDownUrl,setStrDownUrl:)) NSString* JV2_PROP_NM(r,2,strDownUrl);
@property (nonatomic, retain, JV2_PROP_GS_V2(strUpgradeMsg,setStrUpgradeMsg:)) NSString* JV2_PROP_NM(r,3,strUpgradeMsg);
@property (nonatomic, retain, JV2_PROP_GS_V2(size,setSize:)) NSString* JV2_PROP_NM(r,4,size);
@property (nonatomic, retain, JV2_PROP_GS_V2(vImgs,setVImgs:)) NSArray* JV2_PROP_EX(r,5,vImgs,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(date,setDate:)) NSString* JV2_PROP_NM(r,6,date);

@end
