// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/chat.jce'
// **********************************************************************

#import "ApolloTRespSendChatMessage.h"

@implementation ApolloTRespSendChatMessage

@synthesize JV2_PROP_NM(r,0,index);

+ (void)initialize
{
    if (self == [ApolloTRespSendChatMessage class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespSendChatMessage";
}

@end
