// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTStuctClassTeacher.h"

@implementation ApolloTStuctClassTeacher

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,subject);
@synthesize JV2_PROP_NM(r,2,type);
@synthesize JV2_PROP_NM(r,3,creationtime);

+ (void)initialize
{
    if (self == [ApolloTStuctClassTeacher class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(subject) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TStuctClassTeacher";
}

@end
