// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTSingleStudentParentItem.h"

@interface ApolloTReqOmsEditStudent : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(vItem,setVItem:)) NSArray* JV2_PROP_EX(r,2,vItem,VOApolloTSingleStudentParentItem);
@property (nonatomic, retain, JV2_PROP_GS_V2(vCids,setVCids:)) NSArray* JV2_PROP_EX(r,3,vCids,VONSNumber);

@end
