// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTClientReceiveNoticeIndex : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(targeterid,setTargeterid:)) NSString* JV2_PROP_NM(r,0,targeterid);
@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt64 JV2_PROP_NM(r,1,index);
@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,2,uid);

@end
