// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqAlipayNotifyResult : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(notify_time,setNotify_time:)) NSString* JV2_PROP_NM(r,0,notify_time);
@property (nonatomic, retain, JV2_PROP_GS_V2(notify_type,setNotify_type:)) NSString* JV2_PROP_NM(r,1,notify_type);
@property (nonatomic, retain, JV2_PROP_GS_V2(notify_id,setNotify_id:)) NSString* JV2_PROP_NM(r,2,notify_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(sign_type,setSign_type:)) NSString* JV2_PROP_NM(r,3,sign_type);
@property (nonatomic, retain, JV2_PROP_GS_V2(sign,setSign:)) NSString* JV2_PROP_NM(r,4,sign);
@property (nonatomic, retain, JV2_PROP_GS_V2(out_trade_no,setOut_trade_no:)) NSString* JV2_PROP_NM(r,5,out_trade_no);
@property (nonatomic, retain, JV2_PROP_GS_V2(subject,setSubject:)) NSString* JV2_PROP_NM(r,6,subject);
@property (nonatomic, retain, JV2_PROP_GS_V2(payment_type,setPayment_type:)) NSString* JV2_PROP_NM(r,7,payment_type);
@property (nonatomic, retain, JV2_PROP_GS_V2(trade_no,setTrade_no:)) NSString* JV2_PROP_NM(r,8,trade_no);
@property (nonatomic, retain, JV2_PROP_GS_V2(trade_status,setTrade_status:)) NSString* JV2_PROP_NM(r,9,trade_status);
@property (nonatomic, retain, JV2_PROP_GS_V2(seller_id,setSeller_id:)) NSString* JV2_PROP_NM(r,10,seller_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(seller_email,setSeller_email:)) NSString* JV2_PROP_NM(r,11,seller_email);
@property (nonatomic, retain, JV2_PROP_GS_V2(buyer_id,setBuyer_id:)) NSString* JV2_PROP_NM(r,12,buyer_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(buyer_email,setBuyer_email:)) NSString* JV2_PROP_NM(r,13,buyer_email);
@property (nonatomic, retain, JV2_PROP_GS_V2(total_fee,setTotal_fee:)) NSString* JV2_PROP_NM(r,14,total_fee);
@property (nonatomic, retain, JV2_PROP_GS_V2(quantity,setQuantity:)) NSString* JV2_PROP_NM(r,15,quantity);
@property (nonatomic, retain, JV2_PROP_GS_V2(price,setPrice:)) NSString* JV2_PROP_NM(r,16,price);
@property (nonatomic, retain, JV2_PROP_GS_V2(body,setBody:)) NSString* JV2_PROP_NM(r,17,body);
@property (nonatomic, retain, JV2_PROP_GS_V2(gmt_create,setGmt_create:)) NSString* JV2_PROP_NM(r,18,gmt_create);
@property (nonatomic, retain, JV2_PROP_GS_V2(gmt_payment,setGmt_payment:)) NSString* JV2_PROP_NM(r,19,gmt_payment);
@property (nonatomic, retain, JV2_PROP_GS_V2(is_total_fee_adjust,setIs_total_fee_adjust:)) NSString* JV2_PROP_NM(r,20,is_total_fee_adjust);
@property (nonatomic, retain, JV2_PROP_GS_V2(use_coupon,setUse_coupon:)) NSString* JV2_PROP_NM(r,21,use_coupon);
@property (nonatomic, retain, JV2_PROP_GS_V2(discount,setDiscount:)) NSString* JV2_PROP_NM(r,22,discount);
@property (nonatomic, retain, JV2_PROP_GS_V2(refund_status,setRefund_status:)) NSString* JV2_PROP_NM(r,23,refund_status);
@property (nonatomic, retain, JV2_PROP_GS_V2(gmt_refund,setGmt_refund:)) NSString* JV2_PROP_NM(r,24,gmt_refund);

@end
