// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTBanbanDailyPaperMessageBox.h"

@implementation ApolloTBanbanDailyPaperMessageBox

@synthesize JV2_PROP_NM(r,0,count);
@synthesize JV2_PROP_EX(r,1,messages,VOApolloTBanbanDailyPaperMessage);

+ (void)initialize
{
    if (self == [ApolloTBanbanDailyPaperMessageBox class]) {
        [ApolloTBanbanDailyPaperMessage initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(messages) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TBanbanDailyPaperMessageBox";
}

@end
