// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/PullNewUserActivity.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTPullNewCid.h"

@interface ApolloTRespPullNewGetUserTeachCid : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vPNC,setVPNC:)) NSArray* JV2_PROP_EX(r,0,vPNC,VOApolloTPullNewCid);

@end
