// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqSendZoneMsg.h"

@implementation ApolloTReqSendZoneMsg

@synthesize JV2_PROP_NM(r,0,senderId);
@synthesize JV2_PROP_NM(r,1,content);
@synthesize JV2_PROP_NM(r,2,describe);
@synthesize JV2_PROP_NM(r,3,openStatus);
@synthesize JV2_PROP_NM(r,4,location);
@synthesize JV2_PROP_NM(r,5,publishTime);

+ (void)initialize
{
    if (self == [ApolloTReqSendZoneMsg class]) {
        [ApolloTZoneMsgContent initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(senderId) = DefaultJceString;
        JV2_PROP(content) = [ApolloTZoneMsgContent object];
        JV2_PROP(describe) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSendZoneMsg";
}

@end
