// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTChild.h"
#import "ApolloTThirdAccount.h"
#import "ApolloTUser.h"
#import "ApolloTUserLabel.h"

@interface ApolloTUserBase : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(tUser,setTUser:)) ApolloTUser* JV2_PROP_NM(r,0,tUser);
@property (nonatomic, retain, JV2_PROP_GS_V2(vChildrenMain,setVChildrenMain:)) NSArray* JV2_PROP_EX(r,1,vChildrenMain,VOApolloTChild);
@property (nonatomic, retain, JV2_PROP_GS_V2(vChildrenForcus,setVChildrenForcus:)) NSArray* JV2_PROP_EX(r,2,vChildrenForcus,VOApolloTChild);
@property (nonatomic, assign, JV2_PROP_GS_V2(isRelatedClass,setIsRelatedClass:)) JceInt16 JV2_PROP_NM(o,3,isRelatedClass);
@property (nonatomic, assign, JV2_PROP_GS_V2(timestamp,setTimestamp:)) JceInt64 JV2_PROP_NM(o,4,timestamp);
@property (nonatomic, retain, JV2_PROP_GS_V2(banban,setBanban:)) NSString* JV2_PROP_NM(o,5,banban);
@property (nonatomic, retain, JV2_PROP_GS_V2(vThirdAccounts,setVThirdAccounts:)) NSArray* JV2_PROP_EX(o,6,vThirdAccounts,VOApolloTThirdAccount);
@property (nonatomic, assign, JV2_PROP_GS_V2(canSetBanBanNo,setCanSetBanBanNo:)) JceInt16 JV2_PROP_NM(o,7,canSetBanBanNo);
@property (nonatomic, retain, JV2_PROP_GS_V2(userdesc,setUserdesc:)) NSString* JV2_PROP_NM(o,8,userdesc);
@property (nonatomic, retain, JV2_PROP_GS_V2(vLabels,setVLabels:)) NSArray* JV2_PROP_EX(o,9,vLabels,VOApolloTUserLabel);

@end
