// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTRecSchoolGroup.h"

@interface ApolloTRespGetRecSchoolClass : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vRecSchoolGroups,setVRecSchoolGroups:)) NSArray* JV2_PROP_EX(r,0,vRecSchoolGroups,VOApolloTRecSchoolGroup);

@end
