// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTRespGetAuthTeacherApplicationList.h"

@implementation ApolloTRespGetAuthTeacherApplicationList

@synthesize JV2_PROP_EX(r,0,vATA,VOApolloTAuthTeacherApplication);
@synthesize JV2_PROP_NM(r,1,total);

+ (void)initialize
{
    if (self == [ApolloTRespGetAuthTeacherApplicationList class]) {
        [ApolloTAuthTeacherApplication initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vATA) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetAuthTeacherApplicationList";
}

@end
