// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTGrade : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(gid,setGid:)) JceInt32 JV2_PROP_NM(r,0,gid);
@property (nonatomic, retain, JV2_PROP_GS_V2(gName,setGName:)) NSString* JV2_PROP_NM(r,1,gName);
@property (nonatomic, assign, JV2_PROP_GS_V2(stid,setStid:)) JceInt32 JV2_PROP_NM(r,2,stid);

@end
