// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqSetPassword.h"

@implementation ApolloTReqSetPassword

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,oldPwd);
@synthesize JV2_PROP_NM(r,2,newPwd);

+ (void)initialize
{
    if (self == [ApolloTReqSetPassword class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(oldPwd) = DefaultJceString;
        JV2_PROP(newPwd) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSetPassword";
}

@end
