// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqChildTestJoinClass.h"

@implementation ApolloTReqChildTestJoinClass

@synthesize JV2_PROP_NM(r,0,studentuid);
@synthesize JV2_PROP_NM(r,1,studentname);
@synthesize JV2_PROP_NM(r,2,cid);

+ (void)initialize
{
    if (self == [ApolloTReqChildTestJoinClass class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(studentuid) = DefaultJceString;
        JV2_PROP(studentname) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqChildTestJoinClass";
}

@end
