// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqSendBanBanTeamMessage.h"

@implementation ApolloTReqSendBanBanTeamMessage

@synthesize JV2_PROP_NM(o,0,message);
@synthesize JV2_PROP_NM(o,1,type);
@synthesize JV2_PROP_NM(o,2,userType);
@synthesize JV2_PROP_NM(o,3,region);

+ (void)initialize
{
    if (self == [ApolloTReqSendBanBanTeamMessage class]) {
        [ApolloTChatMessage initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSendBanBanTeamMessage";
}

@end
