// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTUser.h"

@implementation ApolloTUser

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_NM(r,2,sex);
@synthesize JV2_PROP_NM(r,3,icon);
@synthesize JV2_PROP_NM(r,4,signature);
@synthesize JV2_PROP_NM(r,5,mobilephone);
@synthesize JV2_PROP_NM(r,6,address);
@synthesize JV2_PROP_NM(r,7,identity);
@synthesize JV2_PROP_NM(o,8,addressId);
@synthesize JV2_PROP_NM(o,9,teacherauth);
@synthesize JV2_PROP_NM(o,10,issmsauth);
@synthesize JV2_PROP_NM(o,11,usertype);
@synthesize JV2_PROP_NM(o,12,userschoolname);

+ (void)initialize
{
    if (self == [ApolloTUser class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(icon) = DefaultJceString;
        JV2_PROP(signature) = DefaultJceString;
        JV2_PROP(mobilephone) = DefaultJceString;
        JV2_PROP(address) = DefaultJceString;
        JV2_PROP(userschoolname) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TUser";
}

@end
