// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTStructStudentGuardian : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(role,setRole:)) NSString* JV2_PROP_NM(r,1,role);
@property (nonatomic, assign, JV2_PROP_GS_V2(main,setMain:)) JceInt16 JV2_PROP_NM(r,2,main);

@end
