// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpProto.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTCommonResponseAuth : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(mobile,setMobile:)) NSString* JV2_PROP_NM(r,0,mobile);

@end
