// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTSchool : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(scid,setScid:)) JceInt32 JV2_PROP_NM(r,0,scid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(city,setCity:)) NSString* JV2_PROP_NM(o,2,city);
@property (nonatomic, retain, JV2_PROP_GS_V2(region,setRegion:)) NSString* JV2_PROP_NM(o,3,region);
@property (nonatomic, assign, JV2_PROP_GS_V2(aid,setAid:)) JceInt32 JV2_PROP_NM(o,4,aid);

@end
