// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTRespGetClassGrade.h"

@implementation ApolloTRespGetClassGrade

@synthesize JV2_PROP_NM(r,0,tGrade);

+ (void)initialize
{
    if (self == [ApolloTRespGetClassGrade class]) {
        [ApolloTGrade initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(tGrade) = [ApolloTGrade object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetClassGrade";
}

@end
