// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/connect.jce'
// **********************************************************************

#import "ApolloTRespAuth.h"

@implementation ApolloTRespAuth

@synthesize JV2_PROP_NM(r,0,iRet);
@synthesize JV2_PROP_NM(r,1,sMsg);
@synthesize JV2_PROP_NM(r,2,iTime);

+ (void)initialize
{
    if (self == [ApolloTRespAuth class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sMsg) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespAuth";
}

@end
