// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/chat.jce'
// **********************************************************************

#import "ApolloTRespGetChatMessageBoxs.h"

@implementation ApolloTRespGetChatMessageBoxs

@synthesize JV2_PROP_EX(r,0,vMessageboxs,VOApolloTChatMessageBox);

+ (void)initialize
{
    if (self == [ApolloTRespGetChatMessageBoxs class]) {
        [ApolloTChatMessageBox initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vMessageboxs) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetChatMessageBoxs";
}

@end
