// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTTeacher : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(photo,setPhoto:)) NSString* JV2_PROP_NM(o,2,photo);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt32 JV2_PROP_NM(o,3,type);
@property (nonatomic, assign, JV2_PROP_GS_V2(sex,setSex:)) JceInt32 JV2_PROP_NM(o,4,sex);
@property (nonatomic, retain, JV2_PROP_GS_V2(mobilePhone,setMobilePhone:)) NSString* JV2_PROP_NM(o,5,mobilePhone);
@property (nonatomic, retain, JV2_PROP_GS_V2(subject,setSubject:)) NSString* JV2_PROP_NM(o,6,subject);
@property (nonatomic, retain, JV2_PROP_GS_V2(joinTime,setJoinTime:)) NSString* JV2_PROP_NM(o,7,joinTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(icon,setIcon:)) JceInt32 JV2_PROP_NM(o,8,icon);
@property (nonatomic, assign, JV2_PROP_GS_V2(teacherauth,setTeacherauth:)) JceInt16 JV2_PROP_NM(o,9,teacherauth);
@property (nonatomic, assign, JV2_PROP_GS_V2(loginstatus,setLoginstatus:)) JceInt32 JV2_PROP_NM(o,10,loginstatus);

@end
