// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTZonePicture.h"

@implementation ApolloTZonePicture

@synthesize JV2_PROP_NM(r,0,height);
@synthesize JV2_PROP_NM(r,1,width);
@synthesize JV2_PROP_NM(r,2,url);

+ (void)initialize
{
    if (self == [ApolloTZonePicture class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(url) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TZonePicture";
}

@end
