// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTZoneAction.h"

@implementation ApolloTZoneAction

@synthesize JV2_PROP_NM(r,0,type);
@synthesize JV2_PROP_NM(r,1,url);
@synthesize JV2_PROP_NM(o,2,btncolor);
@synthesize JV2_PROP_NM(o,3,text);
@synthesize JV2_PROP_NM(o,4,btnType);
@synthesize JV2_PROP_NM(o,5,btnUrl);

+ (void)initialize
{
    if (self == [ApolloTZoneAction class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(url) = DefaultJceString;
        JV2_PROP(text) = DefaultJceString;
        JV2_PROP(btnUrl) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TZoneAction";
}

@end
