// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqBatchImportClassStudentGuardian.h"

@implementation ApolloTReqBatchImportClassStudentGuardian

@synthesize JV2_PROP_EX(r,0,vClassStudentItem,VOApolloTImportClassStudentGuardianItem);

+ (void)initialize
{
    if (self == [ApolloTReqBatchImportClassStudentGuardian class]) {
        [ApolloTImportClassStudentGuardianItem initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vClassStudentItem) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqBatchImportClassStudentGuardian";
}

@end
