// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqVerifyJoinClass.h"

@implementation ApolloTReqVerifyJoinClass

@synthesize JV2_PROP_NM(r,0,auditRecordId);
@synthesize JV2_PROP_NM(r,1,flag);
@synthesize JV2_PROP_NM(r,2,cid);

+ (void)initialize
{
    if (self == [ApolloTReqVerifyJoinClass class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(auditRecordId) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqVerifyJoinClass";
}

@end
