// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTReqSendNotice.h"

@implementation ApolloTReqSendNotice

@synthesize JV2_PROP_NM(r,0,notice);

+ (void)initialize
{
    if (self == [ApolloTReqSendNotice class]) {
        [ApolloTNotice initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(notice) = [ApolloTNotice object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSendNotice";
}

@end
