// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTRespGetClassMember.h"

@implementation ApolloTRespGetClassMember

@synthesize JV2_PROP_EX(o,0,vStudents,VOApolloTStudent);
@synthesize JV2_PROP_EX(o,1,vTeachers,VOApolloTTeacher);

+ (void)initialize
{
    if (self == [ApolloTRespGetClassMember class]) {
        [ApolloTStudent initialize];
        [ApolloTTeacher initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetClassMember";
}

@end
