// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/audit.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTAuditRecord.h"

@interface ApolloTReqPushAudit : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vAudit,setVAudit:)) NSArray* JV2_PROP_EX(r,0,vAudit,VOApolloTAuditRecord);

@end
