// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/chat.jce'
// **********************************************************************

#import "ApolloTClientReceiveChatIndex.h"

@implementation ApolloTClientReceiveChatIndex

@synthesize JV2_PROP_NM(r,0,targeterid);
@synthesize JV2_PROP_NM(r,1,index);
@synthesize JV2_PROP_NM(r,2,uid);
@synthesize JV2_PROP_NM(r,3,type);

+ (void)initialize
{
    if (self == [ApolloTClientReceiveChatIndex class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(targeterid) = DefaultJceString;
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TClientReceiveChatIndex";
}

@end
