// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneAdv.h"
#import "ApolloTZoneObject.h"

@interface ApolloTRespZoneMain : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vTops,setVTops:)) NSArray* JV2_PROP_EX(r,0,vTops,VOApolloTZoneAdv);
@property (nonatomic, retain, JV2_PROP_GS_V2(vHots,setVHots:)) NSArray* JV2_PROP_EX(r,1,vHots,VOApolloTZoneObject);

@end
