// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneMessage.h"

@interface ApolloTRespZoneMessages : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(messages,setMessages:)) NSArray* JV2_PROP_EX(r,0,messages,VOApolloTZoneMessage);

@end
