// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTAdPlace : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(adId,setAdId:)) JceInt32 JV2_PROP_NM(r,0,adId);
@property (nonatomic, assign, JV2_PROP_GS_V2(adType,setAdType:)) JceInt16 JV2_PROP_NM(r,1,adType);
@property (nonatomic, retain, JV2_PROP_GS_V2(title,setTitle:)) NSString* JV2_PROP_NM(o,2,title);
@property (nonatomic, retain, JV2_PROP_GS_V2(pic,setPic:)) NSString* JV2_PROP_NM(o,3,pic);
@property (nonatomic, retain, JV2_PROP_GS_V2(details,setDetails:)) NSString* JV2_PROP_NM(o,4,details);
@property (nonatomic, assign, JV2_PROP_GS_V2(money,setMoney:)) JceInt32 JV2_PROP_NM(o,5,money);
@property (nonatomic, assign, JV2_PROP_GS_V2(dayclick,setDayclick:)) JceInt32 JV2_PROP_NM(o,6,dayclick);
@property (nonatomic, assign, JV2_PROP_GS_V2(daymaxclick,setDaymaxclick:)) JceInt32 JV2_PROP_NM(o,7,daymaxclick);
@property (nonatomic, assign, JV2_PROP_GS_V2(adNo,setAdNo:)) JceInt32 JV2_PROP_NM(o,8,adNo);

@end
