// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Adapte.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespWebSmsInvitation : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(count,setCount:)) JceInt32 JV2_PROP_NM(r,0,count);

@end
