// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqEditLabel : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(id,setId:)) JceInt32 JV2_PROP_NM(r,0,id);
@property (nonatomic, assign, JV2_PROP_GS_V2(flag,setFlag:)) JceInt32 JV2_PROP_NM(r,1,flag);
@property (nonatomic, retain, JV2_PROP_GS_V2(userlabel,setUserlabel:)) NSString* JV2_PROP_NM(r,2,userlabel);

@end
