// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTNoticeMessage.h"

@interface ApolloTRespGetSingleNoticeMsg : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(NoticeMsg,setNoticeMsg:)) ApolloTNoticeMessage* JV2_PROP_NM(r,0,NoticeMsg);

@end
