// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTNotice.h"

@interface ApolloTReqSendEurgencyNotice : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(notice,setNotice:)) ApolloTNotice* JV2_PROP_NM(r,0,notice);

@end
