// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTAddSingleTeacherClassItem.h"

@interface ApolloTReqOmsAddSingleTeacher : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(mobilePhone,setMobilePhone:)) NSString* JV2_PROP_NM(r,0,mobilePhone);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(vItem,setVItem:)) NSArray* JV2_PROP_EX(r,2,vItem,VOApolloTAddSingleTeacherClassItem);

@end
