// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqConsume : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(uidName,setUidName:)) NSString* JV2_PROP_NM(r,1,uidName);
@property (nonatomic, assign, JV2_PROP_GS_V2(cardid,setCardid:)) JceInt64 JV2_PROP_NM(r,2,cardid);
@property (nonatomic, assign, JV2_PROP_GS_V2(optype,setOptype:)) JceInt32 JV2_PROP_NM(r,3,optype);
@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(o,4,cid);

@end
