// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Package.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloDIRECTION_TYPE_DIRECTION_UP = 1,
    ApolloDIRECTION_TYPE_DIRECTION_DOWN = 2,
    ApolloDIRECTION_TYPE_DIRECTION_FORCE = -1,
    ApolloDIRECTION_TYPE_DIRECTION_All = -2
};
#define ApolloDIRECTION_TYPE NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloDIRECTION_TYPEHelper: JceEnumHelper

+ (NSString *)etos:(ApolloDIRECTION_TYPE)e;
+ (ApolloDIRECTION_TYPE)stoe:(NSString *)s;

@end

#endif
