// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqPublishTopAdv.h"

@implementation ApolloTReqPublishTopAdv

@synthesize JV2_PROP_NM(r,0,adv);
@synthesize JV2_PROP_NM(r,1,location);

+ (void)initialize
{
    if (self == [ApolloTReqPublishTopAdv class]) {
        [ApolloTZoneAdv initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(adv) = [ApolloTZoneAdv object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqPublishTopAdv";
}

@end
