// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/login.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTSession : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(session,setSession:)) NSString* JV2_PROP_NM(r,0,session);
@property (nonatomic, retain, JV2_PROP_GS_V2(devicecode,setDevicecode:)) NSString* JV2_PROP_NM(r,1,devicecode);
@property (nonatomic, assign, JV2_PROP_GS_V2(timestamp,setTimestamp:)) JceInt64 JV2_PROP_NM(r,2,timestamp);
@property (nonatomic, retain, JV2_PROP_GS_V2(clientType,setClientType:)) NSString* JV2_PROP_NM(r,3,clientType);
@property (nonatomic, retain, JV2_PROP_GS_V2(iosToken,setIosToken:)) NSString* JV2_PROP_NM(r,4,iosToken);
@property (nonatomic, retain, JV2_PROP_GS_V2(version,setVersion:)) NSString* JV2_PROP_NM(r,5,version);
@property (nonatomic, assign, JV2_PROP_GS_V2(status,setStatus:)) JceInt32 JV2_PROP_NM(r,6,status);
@property (nonatomic, retain, JV2_PROP_GS_V2(phonetype,setPhonetype:)) NSString* JV2_PROP_NM(r,7,phonetype);
@property (nonatomic, retain, JV2_PROP_GS_V2(pushendpoint,setPushendpoint:)) NSString* JV2_PROP_NM(o,8,pushendpoint);
@property (nonatomic, assign, JV2_PROP_GS_V2(logstatus,setLogstatus:)) JceInt32 JV2_PROP_NM(o,9,logstatus);

@end
