// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/chat.jce'
// **********************************************************************

#import "ApolloTReqSendChatMessage.h"

@implementation ApolloTReqSendChatMessage

@synthesize JV2_PROP_NM(r,0,message);

+ (void)initialize
{
    if (self == [ApolloTReqSendChatMessage class]) {
        [ApolloTChatMessage initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(message) = [ApolloTChatMessage object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSendChatMessage";
}

@end
