// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTSchoolInfo : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(sid,setSid:)) JceInt32 JV2_PROP_NM(r,0,sid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(aid,setAid:)) JceInt32 JV2_PROP_NM(r,2,aid);
@property (nonatomic, assign, JV2_PROP_GS_V2(createtype,setCreatetype:)) JceInt16 JV2_PROP_NM(r,3,createtype);
@property (nonatomic, assign, JV2_PROP_GS_V2(smsnum,setSmsnum:)) JceInt32 JV2_PROP_NM(r,4,smsnum);
@property (nonatomic, retain, JV2_PROP_GS_V2(schoolcode,setSchoolcode:)) NSString* JV2_PROP_NM(r,5,schoolcode);
@property (nonatomic, assign, JV2_PROP_GS_V2(isauth,setIsauth:)) JceInt16 JV2_PROP_NM(r,6,isauth);
@property (nonatomic, assign, JV2_PROP_GS_V2(buysms,setBuysms:)) JceInt32 JV2_PROP_NM(r,7,buysms);
@property (nonatomic, retain, JV2_PROP_GS_V2(pingyin,setPingyin:)) NSString* JV2_PROP_NM(r,8,pingyin);

@end
