// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/audit.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloCLIENT_TYPE.h"

@interface ApolloTReqUpdateAuditRecord : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(auditRecordId,setAuditRecordId:)) NSString* JV2_PROP_NM(r,1,auditRecordId);
@property (nonatomic, assign, JV2_PROP_GS_V2(clientType,setClientType:)) ApolloCLIENT_TYPE JV2_PROP_NM(r,2,clientType);
@property (nonatomic, assign, JV2_PROP_GS_V2(status,setStatus:)) JceInt32 JV2_PROP_NM(r,3,status);

@end
