// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqSetOfficialAccount.h"

@implementation ApolloTReqSetOfficialAccount

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_NM(r,2,sex);
@synthesize JV2_PROP_NM(r,3,teacherauth);
@synthesize JV2_PROP_NM(r,4,photo);

+ (void)initialize
{
    if (self == [ApolloTReqSetOfficialAccount class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(photo) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSetOfficialAccount";
}

@end
