// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTReqAppSendNoticeDetail.h"

@implementation ApolloTReqAppSendNoticeDetail

@synthesize JV2_PROP_NM(r,0,noticeid);

+ (void)initialize
{
    if (self == [ApolloTReqAppSendNoticeDetail class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(noticeid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqAppSendNoticeDetail";
}

@end
