// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTZoneAdv.h"

@implementation ApolloTZoneAdv

@synthesize JV2_PROP_NM(r,0,aid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_NM(r,2,title);
@synthesize JV2_PROP_NM(r,3,describe);
@synthesize JV2_PROP_NM(r,4,pic);
@synthesize JV2_PROP_NM(r,5,likeNum);
@synthesize JV2_PROP_NM(r,6,shareNum);
@synthesize JV2_PROP_NM(r,7,url);
@synthesize JV2_PROP_NM(r,8,actionType);
@synthesize JV2_PROP_NM(r,9,publishTime);
@synthesize JV2_PROP_NM(r,10,sender);
@synthesize JV2_PROP_NM(o,11,picHeight);
@synthesize JV2_PROP_NM(o,12,picWidth);

+ (void)initialize
{
    if (self == [ApolloTZoneAdv class]) {
        [ApolloTZoneSenderObject initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(title) = DefaultJceString;
        JV2_PROP(describe) = DefaultJceString;
        JV2_PROP(pic) = DefaultJceString;
        JV2_PROP(url) = DefaultJceString;
        JV2_PROP(sender) = [ApolloTZoneSenderObject object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TZoneAdv";
}

@end
