// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/chat.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTChatMessage.h"

@interface ApolloTReqSendChatMessage : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(message,setMessage:)) ApolloTChatMessage* JV2_PROP_NM(r,0,message);

@end
