// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTClassFeeCard.h"

@interface ApolloTRespJoinClassFeeCardActivity : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(result,setResult:)) JceInt32 JV2_PROP_NM(r,0,result);
@property (nonatomic, retain, JV2_PROP_GS_V2(card,setCard:)) ApolloTClassFeeCard* JV2_PROP_NM(o,1,card);

@end
