// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTRespGetSingleNoticeMsg.h"

@implementation ApolloTRespGetSingleNoticeMsg

@synthesize JV2_PROP_NM(r,0,NoticeMsg);

+ (void)initialize
{
    if (self == [ApolloTRespGetSingleNoticeMsg class]) {
        [ApolloTNoticeMessage initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(NoticeMsg) = [ApolloTNoticeMessage object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetSingleNoticeMsg";
}

@end
