// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZonePictureText.h"
#import "ApolloTZoneSenderObject.h"
#import "ApolloTZoneTargeterObjcet.h"

@interface ApolloTZoneCommentContent : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(msgId,setMsgId:)) NSString* JV2_PROP_NM(r,0,msgId);
@property (nonatomic, retain, JV2_PROP_GS_V2(sender,setSender:)) ApolloTZoneSenderObject* JV2_PROP_NM(r,1,sender);
@property (nonatomic, retain, JV2_PROP_GS_V2(targeter,setTargeter:)) ApolloTZoneTargeterObjcet* JV2_PROP_NM(r,2,targeter);
@property (nonatomic, retain, JV2_PROP_GS_V2(content,setContent:)) NSArray* JV2_PROP_EX(r,3,content,VOApolloTZonePictureText);
@property (nonatomic, assign, JV2_PROP_GS_V2(likeCount,setLikeCount:)) JceInt32 JV2_PROP_NM(r,4,likeCount);
@property (nonatomic, assign, JV2_PROP_GS_V2(sharecount,setSharecount:)) JceInt32 JV2_PROP_NM(o,5,sharecount);
@property (nonatomic, retain, JV2_PROP_GS_V2(simpleDesp,setSimpleDesp:)) NSString* JV2_PROP_NM(o,6,simpleDesp);

@end
