// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqZoneMsgDetail : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(msgid,setMsgid:)) JceInt64 JV2_PROP_NM(r,1,msgid);
@property (nonatomic, assign, JV2_PROP_GS_V2(reqType,setReqType:)) JceInt32 JV2_PROP_NM(o,2,reqType);

@end
