// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "ApolloTClassFee.h"

@implementation ApolloTClassFee

@synthesize JV2_PROP_NM(r,0,cid);
@synthesize JV2_PROP_NM(r,1,dTotalIncome);
@synthesize JV2_PROP_NM(r,2,dBalance);
@synthesize JV2_PROP_NM(r,3,dMax);
@synthesize JV2_PROP_NM(r,4,dToday);
@synthesize JV2_PROP_NM(r,5,createtime);
@synthesize JV2_PROP_NM(r,6,updatetime);
@synthesize JV2_PROP_NM(o,7,sURL);

+ (void)initialize
{
    if (self == [ApolloTClassFee class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sURL) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TClassFee";
}

@end
