// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/audit.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloEClassTrendsType_ECTT_ALL = 0,
    ApolloEClassTrendsType_ECTT_PARTRIARCH_JOIN = 1,
    ApolloEClassTrendsType_ECTT_TEACHER_JOIN = 2
};
#define ApolloEClassTrendsType NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloEClassTrendsTypeHelper: JceEnumHelper

+ (NSString *)etos:(ApolloEClassTrendsType)e;
+ (ApolloEClassTrendsType)stoe:(NSString *)s;

@end

#endif
