// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Bean.jce'
// **********************************************************************

#import "ApolloTRespAcquireBeanInfo.h"

@implementation ApolloTRespAcquireBeanInfo

@synthesize JV2_PROP_NM(r,0,bean);

+ (void)initialize
{
    if (self == [ApolloTRespAcquireBeanInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespAcquireBeanInfo";
}

@end
