// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTRespBanBanDailyIntroduce.h"

@implementation ApolloTRespBanBanDailyIntroduce

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,channelId);
@synthesize JV2_PROP_NM(r,2,senderPicUrl);
@synthesize JV2_PROP_NM(r,3,senderName);
@synthesize JV2_PROP_NM(r,4,introduce);

+ (void)initialize
{
    if (self == [ApolloTRespBanBanDailyIntroduce class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(channelId) = DefaultJceString;
        JV2_PROP(senderPicUrl) = DefaultJceString;
        JV2_PROP(senderName) = DefaultJceString;
        JV2_PROP(introduce) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespBanBanDailyIntroduce";
}

@end
