// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqSetClass.h"

@implementation ApolloTReqSetClass

@synthesize JV2_PROP_NM(r,0,cid);
@synthesize JV2_PROP_NM(r,1,flag);
@synthesize JV2_PROP_NM(o,2,tSchool);
@synthesize JV2_PROP_NM(o,3,validate);
@synthesize JV2_PROP_NM(o,4,cName);
@synthesize JV2_PROP_NM(o,5,uid);
@synthesize JV2_PROP_NM(o,6,gid);
@synthesize JV2_PROP_NM(o,7,stid);

+ (void)initialize
{
    if (self == [ApolloTReqSetClass class]) {
        [ApolloTSchool initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(cName) = DefaultJceString;
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSetClass";
}

@end
