// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespPersonHomePageLike : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(likeNum,setLikeNum:)) JceInt32 JV2_PROP_NM(r,0,likeNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(likeStatus,setLikeStatus:)) JceInt32 JV2_PROP_NM(r,1,likeStatus);

@end
