// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTClassCardInfo.h"

@interface ApolloTRespSearchClass : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vecClass,setVecClass:)) NSArray* JV2_PROP_EX(r,0,vecClass,VOApolloTClassCardInfo);

@end
