// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneSenderObject.h"

@interface ApolloTZoneAdv : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(aid,setAid:)) JceInt64 JV2_PROP_NM(r,0,aid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(title,setTitle:)) NSString* JV2_PROP_NM(r,2,title);
@property (nonatomic, retain, JV2_PROP_GS_V2(describe,setDescribe:)) NSString* JV2_PROP_NM(r,3,describe);
@property (nonatomic, retain, JV2_PROP_GS_V2(pic,setPic:)) NSString* JV2_PROP_NM(r,4,pic);
@property (nonatomic, assign, JV2_PROP_GS_V2(likeNum,setLikeNum:)) JceInt32 JV2_PROP_NM(r,5,likeNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(shareNum,setShareNum:)) JceInt32 JV2_PROP_NM(r,6,shareNum);
@property (nonatomic, retain, JV2_PROP_GS_V2(url,setUrl:)) NSString* JV2_PROP_NM(r,7,url);
@property (nonatomic, assign, JV2_PROP_GS_V2(actionType,setActionType:)) JceInt32 JV2_PROP_NM(r,8,actionType);
@property (nonatomic, assign, JV2_PROP_GS_V2(publishTime,setPublishTime:)) JceInt64 JV2_PROP_NM(r,9,publishTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(sender,setSender:)) ApolloTZoneSenderObject* JV2_PROP_NM(r,10,sender);
@property (nonatomic, assign, JV2_PROP_GS_V2(picHeight,setPicHeight:)) JceInt32 JV2_PROP_NM(o,11,picHeight);
@property (nonatomic, assign, JV2_PROP_GS_V2(picWidth,setPicWidth:)) JceInt32 JV2_PROP_NM(o,12,picWidth);

@end
