// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTRespOmsSearchUserLoginStatus.h"

@implementation ApolloTRespOmsSearchUserLoginStatus

@synthesize JV2_PROP_EX(r,0,mapUidStatus,M09ONSStringONSNumber);

+ (void)initialize
{
    if (self == [ApolloTRespOmsSearchUserLoginStatus class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(mapUidStatus) = DefaultJceDictionary;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespOmsSearchUserLoginStatus";
}

@end
