// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClientProto.jce'
// **********************************************************************

#import "ApolloTClientPackage.h"

@implementation ApolloTClientPackage

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,iSequence);
@synthesize JV2_PROP_NM(r,2,msgBody);

+ (void)initialize
{
    if (self == [ApolloTClientPackage class]) {
        [ApolloTMsgBody initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(msgBody) = [ApolloTMsgBody object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TClientPackage";
}

@end
