// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespBatchImportClassTeacher : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(mapErrXY,setMapErrXY:)) NSDictionary* JV2_PROP_EX(r,0,mapErrXY,M09ONSNumberVONSNumber);

@end
