// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "ApolloTReqRollback.h"

@implementation ApolloTReqRollback

@synthesize JV2_PROP_NM(r,0,lOrderNum);
@synthesize JV2_PROP_NM(r,1,dValue);
@synthesize JV2_PROP_NM(r,2,cid);
@synthesize JV2_PROP_NM(o,3,type);

+ (void)initialize
{
    if (self == [ApolloTReqRollback class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(type) = 4;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqRollback";
}

@end
