// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTSchool.h"

@implementation ApolloTSchool

@synthesize JV2_PROP_NM(r,0,scid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_NM(o,2,city);
@synthesize JV2_PROP_NM(o,3,region);
@synthesize JV2_PROP_NM(o,4,aid);

+ (void)initialize
{
    if (self == [ApolloTSchool class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(city) = DefaultJceString;
        JV2_PROP(region) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TSchool";
}

@end
