// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTRespSendEurgencyNotice.h"

@implementation ApolloTRespSendEurgencyNotice

@synthesize JV2_PROP_NM(r,0,result);
@synthesize JV2_PROP_NM(o,1,sendSmsNum);
@synthesize JV2_PROP_NM(o,2,surplusSmsNum);

+ (void)initialize
{
    if (self == [ApolloTRespSendEurgencyNotice class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespSendEurgencyNotice";
}

@end
