// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Adapte.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqWebSmsInvitation : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vMobilePhone,setVMobilePhone:)) NSArray* JV2_PROP_EX(r,0,vMobilePhone,VONSString);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt32 JV2_PROP_NM(r,1,type);
@property (nonatomic, retain, JV2_PROP_GS_V2(content,setContent:)) NSString* JV2_PROP_NM(r,2,content);

@end
