// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqModifyObjectLocation : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(objectid,setObjectid:)) JceInt64 JV2_PROP_NM(r,1,objectid);
@property (nonatomic, assign, JV2_PROP_GS_V2(Type,setType:)) JceInt32 JV2_PROP_NM(r,2,Type);
@property (nonatomic, assign, JV2_PROP_GS_V2(LocationType,setLocationType:)) JceInt32 JV2_PROP_NM(r,3,LocationType);
@property (nonatomic, assign, JV2_PROP_GS_V2(location,setLocation:)) JceInt32 JV2_PROP_NM(r,4,location);
@property (nonatomic, assign, JV2_PROP_GS_V2(levelId,setLevelId:)) JceInt64 JV2_PROP_NM(r,5,levelId);
@property (nonatomic, assign, JV2_PROP_GS_V2(modifyType,setModifyType:)) JceInt32 JV2_PROP_NM(o,6,modifyType);

@end
