// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqOmsSearchUserLoginStatus.h"

@implementation ApolloTReqOmsSearchUserLoginStatus

@synthesize JV2_PROP_EX(r,0,vUids,VONSString);

+ (void)initialize
{
    if (self == [ApolloTReqOmsSearchUserLoginStatus class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vUids) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqOmsSearchUserLoginStatus";
}

@end
