// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/connect.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTUserBase.h"

@interface ApolloTNotifyUpdateUserBase : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(flag,setFlag:)) JceInt32 JV2_PROP_NM(r,0,flag);
@property (nonatomic, retain, JV2_PROP_GS_V2(userbase,setUserbase:)) ApolloTUserBase* JV2_PROP_NM(o,1,userbase);

@end
