// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTClassFeeCard : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(cardid,setCardid:)) JceInt64 JV2_PROP_NM(r,0,cardid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(category,setCategory:)) JceInt32 JV2_PROP_NM(r,2,category);
@property (nonatomic, assign, JV2_PROP_GS_V2(money,setMoney:)) JceInt32 JV2_PROP_NM(r,3,money);
@property (nonatomic, assign, JV2_PROP_GS_V2(createtime,setCreatetime:)) JceInt64 JV2_PROP_NM(r,4,createtime);
@property (nonatomic, assign, JV2_PROP_GS_V2(endtime,setEndtime:)) JceInt64 JV2_PROP_NM(r,5,endtime);
@property (nonatomic, assign, JV2_PROP_GS_V2(status,setStatus:)) JceInt32 JV2_PROP_NM(r,6,status);
@property (nonatomic, retain, JV2_PROP_GS_V2(ruleid,setRuleid:)) NSString* JV2_PROP_NM(o,7,ruleid);
@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt64 JV2_PROP_NM(o,8,index);

@end
