// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTRespDailyPaperMessages.h"

@implementation ApolloTRespDailyPaperMessages

@synthesize JV2_PROP_EX(r,0,messages,VOApolloTBanbanDailyPaperMessage);

+ (void)initialize
{
    if (self == [ApolloTRespDailyPaperMessages class]) {
        [ApolloTBanbanDailyPaperMessage initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(messages) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespDailyPaperMessages";
}

@end
