// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/audit.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTAuditRecord.h"

@interface ApolloTRespQueryAuditRecord : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vAuditRecord,setVAuditRecord:)) NSArray* JV2_PROP_EX(r,0,vAuditRecord,VOApolloTAuditRecord);
@property (nonatomic, assign, JV2_PROP_GS_V2(total,setTotal:)) JceInt64 JV2_PROP_NM(r,1,total);

@end
