// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTClassGroup.h"

@interface ApolloTRespClassGroups : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vClassGroups,setVClassGroups:)) NSArray* JV2_PROP_EX(r,0,vClassGroups,VOApolloTClassGroup);

@end
