// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqAddClassFeeCard : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(category,setCategory:)) JceInt32 JV2_PROP_NM(r,1,category);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,2,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(money,setMoney:)) JceInt64 JV2_PROP_NM(r,3,money);
@property (nonatomic, assign, JV2_PROP_GS_V2(endtime,setEndtime:)) JceInt64 JV2_PROP_NM(r,4,endtime);

@end
