// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/login.jce'
// **********************************************************************

#import "ApolloTRespCommonLogin.h"

@implementation ApolloTRespCommonLogin

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,sToken);
@synthesize JV2_PROP_NM(r,2,lTime);
@synthesize JV2_PROP_NM(o,3,sDotNetDomain);
@synthesize JV2_PROP_NM(o,4,sApolloDomain);
@synthesize JV2_PROP_NM(o,5,sDotNetIPPort);
@synthesize JV2_PROP_NM(o,6,sApolloIPPort);
@synthesize JV2_PROP_NM(o,7,user);

+ (void)initialize
{
    if (self == [ApolloTRespCommonLogin class]) {
        [ApolloTUserBase initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(sToken) = DefaultJceString;
        JV2_PROP(sDotNetDomain) = DefaultJceString;
        JV2_PROP(sApolloDomain) = DefaultJceString;
        JV2_PROP(sDotNetIPPort) = DefaultJceString;
        JV2_PROP(sApolloIPPort) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespCommonLogin";
}

@end
