// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTRespPushDailyPaperMessageBox.h"

@implementation ApolloTRespPushDailyPaperMessageBox

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,channelId);
@synthesize JV2_PROP_NM(r,2,pushLocation);

+ (void)initialize
{
    if (self == [ApolloTRespPushDailyPaperMessageBox class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(channelId) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespPushDailyPaperMessageBox";
}

@end
