// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClientProto.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespCommon : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iRet,setIRet:)) JceInt32 JV2_PROP_NM(r,0,iRet);
@property (nonatomic, retain, JV2_PROP_GS_V2(sMsg,setSMsg:)) NSString* JV2_PROP_NM(r,1,sMsg);
@property (nonatomic, assign, JV2_PROP_GS_V2(lTime,setLTime:)) JceInt64 JV2_PROP_NM(r,2,lTime);

@end
