// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/audit.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloDIRECTION_TYPE.h"

@interface ApolloTReqQueryAuditRecord : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt64 JV2_PROP_NM(r,1,index);
@property (nonatomic, assign, JV2_PROP_GS_V2(flag,setFlag:)) ApolloDIRECTION_TYPE JV2_PROP_NM(r,2,flag);

@end
