// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/PullNewUserActivity.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTPullNewCid : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(r,0,cid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);

@end
