// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpProto.jce'
// **********************************************************************

#import "ApolloTRespPackage.h"

@implementation ApolloTRespPackage

@synthesize JV2_PROP_NM(r,0,nCMDID);
@synthesize JV2_PROP_NM(r,1,iSequence);
@synthesize JV2_PROP_NM(r,2,iResult);
@synthesize JV2_PROP_NM(o,3,sMessage);
@synthesize JV2_PROP_NM(o,4,vecData);

+ (void)initialize
{
    if (self == [ApolloTRespPackage class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sMessage) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespPackage";
}

@end
