// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTAuthTeacherApplication.h"

@interface ApolloTRespGetAuthTeacherApplicationList : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vATA,setVATA:)) NSArray* JV2_PROP_EX(r,0,vATA,VOApolloTAuthTeacherApplication);
@property (nonatomic, assign, JV2_PROP_GS_V2(total,setTotal:)) JceInt32 JV2_PROP_NM(r,1,total);

@end
