// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTRespBatchImportClassTeacher.h"

@implementation ApolloTRespBatchImportClassTeacher

@synthesize JV2_PROP_EX(r,0,mapErrXY,M09ONSNumberVONSNumber);

+ (void)initialize
{
    if (self == [ApolloTRespBatchImportClassTeacher class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(mapErrXY) = DefaultJceDictionary;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespBatchImportClassTeacher";
}

@end
