// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespSendZoneMsg : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(msgid,setMsgid:)) JceInt64 JV2_PROP_NM(r,0,msgid);
@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt64 JV2_PROP_NM(o,1,index);

@end
