// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqAckNoticeStatus : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(noticeid,setNoticeid:)) NSString* JV2_PROP_NM(r,0,noticeid);
@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,1,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(tagid,setTagid:)) NSString* JV2_PROP_NM(r,2,tagid);
@property (nonatomic, assign, JV2_PROP_GS_V2(flag,setFlag:)) JceInt32 JV2_PROP_NM(r,3,flag);

@end
