// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTZoneComment.h"

@implementation ApolloTZoneComment

@synthesize JV2_PROP_NM(r,0,commentId);
@synthesize JV2_PROP_NM(r,1,content);
@synthesize JV2_PROP_NM(r,2,sendTime);
@synthesize JV2_PROP_NM(r,3,hot);
@synthesize JV2_PROP_NM(r,4,index);
@synthesize JV2_PROP_NM(o,5,likeStatus);

+ (void)initialize
{
    if (self == [ApolloTZoneComment class]) {
        [ApolloTZoneCommentContent initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(content) = [ApolloTZoneCommentContent object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TZoneComment";
}

@end
