// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTSameNameChildInClass.h"

@interface ApolloTRespChildTestJoinClass : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vSameNameStudent,setVSameNameStudent:)) NSArray* JV2_PROP_EX(r,0,vSameNameStudent,VOApolloTSameNameChildInClass);

@end
