// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Package.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloSESSION_STATUS_SESSION_NORMAL = 0,
    ApolloSESSION_STATUS_SESSION_LOGOUT = 1,
    ApolloSESSION_STATUS_SESSION_DELETE = 2
};
#define ApolloSESSION_STATUS NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloSESSION_STATUSHelper: JceEnumHelper

+ (NSString *)etos:(ApolloSESSION_STATUS)e;
+ (ApolloSESSION_STATUS)stoe:(NSString *)s;

@end

#endif
