// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqWeiXiUnifiedOrder : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(body,setBody:)) NSString* JV2_PROP_NM(r,0,body);
@property (nonatomic, assign, JV2_PROP_GS_V2(total_fee,setTotal_fee:)) JceInt32 JV2_PROP_NM(r,1,total_fee);
@property (nonatomic, retain, JV2_PROP_GS_V2(spbill_create_ip,setSpbill_create_ip:)) NSString* JV2_PROP_NM(r,2,spbill_create_ip);
@property (nonatomic, retain, JV2_PROP_GS_V2(product_id,setProduct_id:)) NSString* JV2_PROP_NM(r,3,product_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(out_trade_no,setOut_trade_no:)) NSString* JV2_PROP_NM(r,4,out_trade_no);

@end
