// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTNotice.h"

@implementation ApolloTNotice

@synthesize JV2_PROP_NM(r,0,iNoticeId);
@synthesize JV2_PROP_NM(r,1,sSenderId);
@synthesize JV2_PROP_NM(r,2,sSenderPhoto);
@synthesize JV2_PROP_NM(r,3,sSenderTitle);
@synthesize JV2_PROP_EX(r,4,vReceiver,VOApolloTReceiverObject);
@synthesize JV2_PROP_NM(r,5,receiverTitle);
@synthesize JV2_PROP_NM(r,6,iType);
@synthesize JV2_PROP_NM(r,7,tContent);
@synthesize JV2_PROP_NM(r,8,lSendTime);
@synthesize JV2_PROP_NM(r,9,nPlatform);
@synthesize JV2_PROP_NM(o,10,evalute);
@synthesize JV2_PROP_NM(o,11,action);
@synthesize JV2_PROP_NM(o,12,ReceiverNum);
@synthesize JV2_PROP_NM(o,13,readedNum);
@synthesize JV2_PROP_NM(o,14,index);
@synthesize JV2_PROP_NM(o,15,isSendSms);
@synthesize JV2_PROP_NM(o,16,schoolid);
@synthesize JV2_PROP_NM(o,17,schoolName);
@synthesize JV2_PROP_NM(o,18,teacherauth);

+ (void)initialize
{
    if (self == [ApolloTNotice class]) {
        [ApolloTNoticeText initialize];
        [ApolloTReceiverObject initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sSenderId) = DefaultJceString;
        JV2_PROP(sSenderPhoto) = DefaultJceString;
        JV2_PROP(sSenderTitle) = DefaultJceString;
        JV2_PROP(vReceiver) = DefaultJceArray;
        JV2_PROP(receiverTitle) = DefaultJceString;
        JV2_PROP(tContent) = [ApolloTNoticeText object];
        JV2_PROP(schoolName) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TNotice";
}

@end
