// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTClassFeeCardRule : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(ruleid,setRuleid:)) NSString* JV2_PROP_NM(r,0,ruleid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(description,setDescription:)) NSString* JV2_PROP_NM(r,2,description);
@property (nonatomic, assign, JV2_PROP_GS_V2(amount,setAmount:)) JceInt32 JV2_PROP_NM(r,3,amount);
@property (nonatomic, assign, JV2_PROP_GS_V2(createtime,setCreatetime:)) JceInt64 JV2_PROP_NM(r,4,createtime);
@property (nonatomic, assign, JV2_PROP_GS_V2(headcount,setHeadcount:)) JceInt64 JV2_PROP_NM(r,5,headcount);
@property (nonatomic, assign, JV2_PROP_GS_V2(minmoney,setMinmoney:)) JceInt64 JV2_PROP_NM(r,6,minmoney);
@property (nonatomic, assign, JV2_PROP_GS_V2(maxmoney,setMaxmoney:)) JceInt64 JV2_PROP_NM(r,7,maxmoney);
@property (nonatomic, assign, JV2_PROP_GS_V2(averagemoney,setAveragemoney:)) JceInt64 JV2_PROP_NM(r,8,averagemoney);
@property (nonatomic, assign, JV2_PROP_GS_V2(proportion,setProportion:)) JceInt32 JV2_PROP_NM(r,9,proportion);
@property (nonatomic, assign, JV2_PROP_GS_V2(endtime,setEndtime:)) JceInt64 JV2_PROP_NM(r,10,endtime);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt32 JV2_PROP_NM(r,11,type);
@property (nonatomic, assign, JV2_PROP_GS_V2(deleted,setDeleted:)) JceInt32 JV2_PROP_NM(r,12,deleted);
@property (nonatomic, retain, JV2_PROP_GS_V2(activeid,setActiveid:)) NSString* JV2_PROP_NM(r,13,activeid);

@end
