// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneMessageBox.h"

@interface ApolloTReqPushZoneMessageBox : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(messageBox,setMessageBox:)) ApolloTZoneMessageBox* JV2_PROP_NM(r,1,messageBox);
@property (nonatomic, assign, JV2_PROP_GS_V2(readLocation,setReadLocation:)) JceInt64 JV2_PROP_NM(r,2,readLocation);

@end
