// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Adapte.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTWebImportStudentGuardianItem.h"

@interface ApolloTReqWebImportStudentGuardianIntoClass : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(r,0,cid);
@property (nonatomic, retain, JV2_PROP_GS_V2(vStudentItem,setVStudentItem:)) NSArray* JV2_PROP_EX(o,1,vStudentItem,VOApolloTWebImportStudentGuardianItem);

@end
