// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespGetDetailedIdentity : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(isMaster,setIsMaster:)) JceInt16 JV2_PROP_NM(r,0,isMaster);
@property (nonatomic, assign, JV2_PROP_GS_V2(isTeacher,setIsTeacher:)) JceInt16 JV2_PROP_NM(r,1,isTeacher);
@property (nonatomic, assign, JV2_PROP_GS_V2(isPatriarch,setIsPatriarch:)) JceInt16 JV2_PROP_NM(r,2,isPatriarch);
@property (nonatomic, assign, JV2_PROP_GS_V2(isFocus,setIsFocus:)) JceInt16 JV2_PROP_NM(r,3,isFocus);

@end
