// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTClassFee : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(r,0,cid);
@property (nonatomic, assign, JV2_PROP_GS_V2(dTotalIncome,setDTotalIncome:)) JceInt32 JV2_PROP_NM(r,1,dTotalIncome);
@property (nonatomic, assign, JV2_PROP_GS_V2(dBalance,setDBalance:)) JceInt32 JV2_PROP_NM(r,2,dBalance);
@property (nonatomic, assign, JV2_PROP_GS_V2(dMax,setDMax:)) JceInt32 JV2_PROP_NM(r,3,dMax);
@property (nonatomic, assign, JV2_PROP_GS_V2(dToday,setDToday:)) JceInt32 JV2_PROP_NM(r,4,dToday);
@property (nonatomic, assign, JV2_PROP_GS_V2(createtime,setCreatetime:)) JceInt32 JV2_PROP_NM(r,5,createtime);
@property (nonatomic, assign, JV2_PROP_GS_V2(updatetime,setUpdatetime:)) JceInt32 JV2_PROP_NM(r,6,updatetime);
@property (nonatomic, retain, JV2_PROP_GS_V2(sURL,setSURL:)) NSString* JV2_PROP_NM(o,7,sURL);

@end
