// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqSearchClass : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(content,setContent:)) NSString* JV2_PROP_NM(r,0,content);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt16 JV2_PROP_NM(r,1,type);

@end
