// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "ApolloTReqTransfer.h"

@implementation ApolloTReqTransfer

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,strName);
@synthesize JV2_PROP_NM(r,2,cid);
@synthesize JV2_PROP_NM(r,3,dValue);
@synthesize JV2_PROP_NM(o,4,iType);
@synthesize JV2_PROP_NM(o,5,banktype);
@synthesize JV2_PROP_NM(o,6,area);
@synthesize JV2_PROP_NM(o,7,city);
@synthesize JV2_PROP_NM(o,8,subbankname);
@synthesize JV2_PROP_NM(o,9,username);
@synthesize JV2_PROP_NM(o,10,usercard);
@synthesize JV2_PROP_NM(o,11,bankaccount);
@synthesize JV2_PROP_NM(o,12,desc);
@synthesize JV2_PROP_NM(o,13,recmobile);

+ (void)initialize
{
    if (self == [ApolloTReqTransfer class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(strName) = DefaultJceString;
        JV2_PROP(banktype) = DefaultJceString;
        JV2_PROP(area) = DefaultJceString;
        JV2_PROP(city) = DefaultJceString;
        JV2_PROP(subbankname) = DefaultJceString;
        JV2_PROP(username) = DefaultJceString;
        JV2_PROP(usercard) = DefaultJceString;
        JV2_PROP(bankaccount) = DefaultJceString;
        JV2_PROP(desc) = DefaultJceString;
        JV2_PROP(recmobile) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqTransfer";
}

@end
