// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/chat.jce'
// **********************************************************************

#import "ApolloTReqChatGroupSet.h"

@implementation ApolloTReqChatGroupSet

@synthesize JV2_PROP_NM(r,0,cid);
@synthesize JV2_PROP_NM(r,1,flag);
@synthesize JV2_PROP_NM(r,2,uid);

+ (void)initialize
{
    if (self == [ApolloTReqChatGroupSet class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqChatGroupSet";
}

@end
