// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZonePicture.h"
#import "ApolloTZoneSenderObject.h"
#import "ApolloTZoneVideo.h"

@interface ApolloTZoneMsg : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(msgId,setMsgId:)) JceInt64 JV2_PROP_NM(r,0,msgId);
@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt64 JV2_PROP_NM(r,1,index);
@property (nonatomic, retain, JV2_PROP_GS_V2(senderObject,setSenderObject:)) ApolloTZoneSenderObject* JV2_PROP_NM(r,2,senderObject);
@property (nonatomic, retain, JV2_PROP_GS_V2(title,setTitle:)) NSString* JV2_PROP_NM(r,3,title);
@property (nonatomic, retain, JV2_PROP_GS_V2(picurl,setPicurl:)) NSArray* JV2_PROP_EX(o,4,picurl,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(describe,setDescribe:)) NSString* JV2_PROP_NM(o,5,describe);
@property (nonatomic, assign, JV2_PROP_GS_V2(openStatus,setOpenStatus:)) JceInt32 JV2_PROP_NM(o,6,openStatus);
@property (nonatomic, assign, JV2_PROP_GS_V2(createTime,setCreateTime:)) JceInt64 JV2_PROP_NM(o,7,createTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(likeNum,setLikeNum:)) JceInt32 JV2_PROP_NM(o,8,likeNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(viewNum,setViewNum:)) JceInt32 JV2_PROP_NM(o,9,viewNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(commentNum,setCommentNum:)) JceInt32 JV2_PROP_NM(o,10,commentNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(shareNum,setShareNum:)) JceInt32 JV2_PROP_NM(o,11,shareNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(likeStatus,setLikeStatus:)) JceInt32 JV2_PROP_NM(o,12,likeStatus);
@property (nonatomic, assign, JV2_PROP_GS_V2(publishTime,setPublishTime:)) JceInt64 JV2_PROP_NM(o,13,publishTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(hot,setHot:)) JceInt32 JV2_PROP_NM(o,14,hot);
@property (nonatomic, retain, JV2_PROP_GS_V2(picurls,setPicurls:)) NSArray* JV2_PROP_EX(o,15,picurls,VOApolloTZonePicture);
@property (nonatomic, retain, JV2_PROP_GS_V2(videourls,setVideourls:)) NSArray* JV2_PROP_EX(o,16,videourls,VOApolloTZoneVideo);

@end
