// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTAreaInfo : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(aid,setAid:)) JceInt32 JV2_PROP_NM(r,0,aid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(parentid,setParentid:)) JceInt32 JV2_PROP_NM(r,2,parentid);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt16 JV2_PROP_NM(r,3,type);
@property (nonatomic, retain, JV2_PROP_GS_V2(postcode,setPostcode:)) NSString* JV2_PROP_NM(r,4,postcode);
@property (nonatomic, retain, JV2_PROP_GS_V2(areacode,setAreacode:)) NSString* JV2_PROP_NM(r,5,areacode);
@property (nonatomic, retain, JV2_PROP_GS_V2(path,setPath:)) NSString* JV2_PROP_NM(r,6,path);

@end
