// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespBanBanDailyIntroduce : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(channelId,setChannelId:)) NSString* JV2_PROP_NM(r,1,channelId);
@property (nonatomic, retain, JV2_PROP_GS_V2(senderPicUrl,setSenderPicUrl:)) NSString* JV2_PROP_NM(r,2,senderPicUrl);
@property (nonatomic, retain, JV2_PROP_GS_V2(senderName,setSenderName:)) NSString* JV2_PROP_NM(r,3,senderName);
@property (nonatomic, retain, JV2_PROP_GS_V2(introduce,setIntroduce:)) NSString* JV2_PROP_NM(r,4,introduce);

@end
