// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTRespSendZoneMsg.h"

@implementation ApolloTRespSendZoneMsg

@synthesize JV2_PROP_NM(r,0,msgid);
@synthesize JV2_PROP_NM(o,1,index);

+ (void)initialize
{
    if (self == [ApolloTRespSendZoneMsg class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespSendZoneMsg";
}

@end
