// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqCreatClass : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,0,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(sid,setSid:)) JceInt32 JV2_PROP_NM(r,1,sid);
@property (nonatomic, assign, JV2_PROP_GS_V2(classtype,setClasstype:)) JceInt32 JV2_PROP_NM(r,2,classtype);
@property (nonatomic, assign, JV2_PROP_GS_V2(grade,setGrade:)) JceInt32 JV2_PROP_NM(r,3,grade);
@property (nonatomic, retain, JV2_PROP_GS_V2(phone,setPhone:)) NSString* JV2_PROP_NM(r,4,phone);
@property (nonatomic, retain, JV2_PROP_GS_V2(mastername,setMastername:)) NSString* JV2_PROP_NM(r,5,mastername);
@property (nonatomic, assign, JV2_PROP_GS_V2(joinverify,setJoinverify:)) JceInt32 JV2_PROP_NM(r,6,joinverify);

@end
