// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqPublishZone.h"

@implementation ApolloTReqPublishZone

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,zone);
@synthesize JV2_PROP_NM(r,2,location);

+ (void)initialize
{
    if (self == [ApolloTReqPublishZone class]) {
        [ApolloTZoneObject initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(zone) = [ApolloTZoneObject object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqPublishZone";
}

@end
