// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqZoneMsg.h"

@implementation ApolloTReqZoneMsg

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,index);
@synthesize JV2_PROP_NM(r,2,flag);
@synthesize JV2_PROP_NM(r,3,type);
@synthesize JV2_PROP_NM(o,4,tagId);

+ (void)initialize
{
    if (self == [ApolloTReqZoneMsg class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(tagId) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqZoneMsg";
}

@end
