// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTRespBatchUidJoinActive.h"

@implementation ApolloTRespBatchUidJoinActive

@synthesize JV2_PROP_EX(r,0,mapRespJoinActive,M09ONSStringOApolloTRespJoinClassFeeCardActivity);

+ (void)initialize
{
    if (self == [ApolloTRespBatchUidJoinActive class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(mapRespJoinActive) = DefaultJceDictionary;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespBatchUidJoinActive";
}

@end
