// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "ApolloTRespWeiXiQueryOrder.h"

@implementation ApolloTRespWeiXiQueryOrder

@synthesize JV2_PROP_NM(r,0,result_code);
@synthesize JV2_PROP_NM(r,1,trade_type);
@synthesize JV2_PROP_NM(r,2,trade_state);
@synthesize JV2_PROP_NM(r,3,bank_type);
@synthesize JV2_PROP_NM(r,4,total_fee);
@synthesize JV2_PROP_NM(r,5,transaction_id);
@synthesize JV2_PROP_NM(r,6,out_trade_no);
@synthesize JV2_PROP_NM(r,7,time_end);
@synthesize JV2_PROP_NM(r,8,trade_state_desc);

+ (void)initialize
{
    if (self == [ApolloTRespWeiXiQueryOrder class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(result_code) = DefaultJceString;
        JV2_PROP(trade_type) = DefaultJceString;
        JV2_PROP(trade_state) = DefaultJceString;
        JV2_PROP(bank_type) = DefaultJceString;
        JV2_PROP(transaction_id) = DefaultJceString;
        JV2_PROP(out_trade_no) = DefaultJceString;
        JV2_PROP(time_end) = DefaultJceString;
        JV2_PROP(trade_state_desc) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespWeiXiQueryOrder";
}

@end
