// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqBindingThirdAccount.h"

@implementation ApolloTReqBindingThirdAccount

@synthesize JV2_PROP_NM(r,0,flag);
@synthesize JV2_PROP_NM(r,1,type);
@synthesize JV2_PROP_NM(r,2,account);
@synthesize JV2_PROP_NM(r,3,nick);
@synthesize JV2_PROP_NM(r,4,photo);
@synthesize JV2_PROP_NM(r,5,sex);

+ (void)initialize
{
    if (self == [ApolloTReqBindingThirdAccount class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(account) = DefaultJceString;
        JV2_PROP(nick) = DefaultJceString;
        JV2_PROP(photo) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqBindingThirdAccount";
}

@end
