// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "ApolloTRespGetAdPlaces.h"

@implementation ApolloTRespGetAdPlaces

@synthesize JV2_PROP_EX(r,0,vecAdPlaces,VOApolloTAdPlace);

+ (void)initialize
{
    if (self == [ApolloTRespGetAdPlaces class]) {
        [ApolloTAdPlace initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vecAdPlaces) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetAdPlaces";
}

@end
