// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespWeiXiUnifiedOrder : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(result_code,setResult_code:)) NSString* JV2_PROP_NM(r,0,result_code);
@property (nonatomic, retain, JV2_PROP_GS_V2(err_code,setErr_code:)) NSString* JV2_PROP_NM(r,1,err_code);
@property (nonatomic, retain, JV2_PROP_GS_V2(err_code_des,setErr_code_des:)) NSString* JV2_PROP_NM(r,2,err_code_des);
@property (nonatomic, retain, JV2_PROP_GS_V2(prepay_id,setPrepay_id:)) NSString* JV2_PROP_NM(r,3,prepay_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(out_trade_no,setOut_trade_no:)) NSString* JV2_PROP_NM(r,4,out_trade_no);

@end
