// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqTransfer : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(strName,setStrName:)) NSString* JV2_PROP_NM(r,1,strName);
@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(r,2,cid);
@property (nonatomic, assign, JV2_PROP_GS_V2(dValue,setDValue:)) JceInt32 JV2_PROP_NM(r,3,dValue);
@property (nonatomic, assign, JV2_PROP_GS_V2(iType,setIType:)) JceInt32 JV2_PROP_NM(o,4,iType);
@property (nonatomic, retain, JV2_PROP_GS_V2(banktype,setBanktype:)) NSString* JV2_PROP_NM(o,5,banktype);
@property (nonatomic, retain, JV2_PROP_GS_V2(area,setArea:)) NSString* JV2_PROP_NM(o,6,area);
@property (nonatomic, retain, JV2_PROP_GS_V2(city,setCity:)) NSString* JV2_PROP_NM(o,7,city);
@property (nonatomic, retain, JV2_PROP_GS_V2(subbankname,setSubbankname:)) NSString* JV2_PROP_NM(o,8,subbankname);
@property (nonatomic, retain, JV2_PROP_GS_V2(username,setUsername:)) NSString* JV2_PROP_NM(o,9,username);
@property (nonatomic, retain, JV2_PROP_GS_V2(usercard,setUsercard:)) NSString* JV2_PROP_NM(o,10,usercard);
@property (nonatomic, retain, JV2_PROP_GS_V2(bankaccount,setBankaccount:)) NSString* JV2_PROP_NM(o,11,bankaccount);
@property (nonatomic, retain, JV2_PROP_GS_V2(desc,setDesc:)) NSString* JV2_PROP_NM(o,12,desc);
@property (nonatomic, retain, JV2_PROP_GS_V2(recmobile,setRecmobile:)) NSString* JV2_PROP_NM(o,13,recmobile);

@end
