// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTThirdAccount.h"

@implementation ApolloTThirdAccount

@synthesize JV2_PROP_NM(r,0,flag);
@synthesize JV2_PROP_NM(r,1,threeuserid);
@synthesize JV2_PROP_NM(r,2,threeusername);

+ (void)initialize
{
    if (self == [ApolloTThirdAccount class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(threeuserid) = DefaultJceString;
        JV2_PROP(threeusername) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TThirdAccount";
}

@end
