// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTClassOfMember.h"

@implementation ApolloTClassOfMember

@synthesize JV2_PROP_EX(r,0,vStudents,VOApolloTStudent);
@synthesize JV2_PROP_EX(r,1,vTeachers,VOApolloTTeacher);

+ (void)initialize
{
    if (self == [ApolloTClassOfMember class]) {
        [ApolloTStudent initialize];
        [ApolloTTeacher initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vStudents) = DefaultJceArray;
        JV2_PROP(vTeachers) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TClassOfMember";
}

@end
