// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloClassFeeEventID.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation ApolloClassFeeEventIDHelper

+ (NSString *)etos:(ApolloClassFeeEventID)e
{
    switch(e){
        case ApolloClassFeeEventID_EVENT_CREATE: return @"ApolloClassFeeEventID_EVENT_CREATE";
        case ApolloClassFeeEventID_EVENT_ACTIVE: return @"ApolloClassFeeEventID_EVENT_ACTIVE";
        case ApolloClassFeeEventID_EVENT_ADVERT: return @"ApolloClassFeeEventID_EVENT_ADVERT";
        case ApolloClassFeeEventID_EVENT_DEPOSIT: return @"ApolloClassFeeEventID_EVENT_DEPOSIT";
        case ApolloClassFeeEventID_EVENT_ROLLBACK: return @"ApolloClassFeeEventID_EVENT_ROLLBACK";
        case ApolloClassFeeEventID_EVENT_OWN_ADVERT: return @"ApolloClassFeeEventID_EVENT_OWN_ADVERT";
        case ApolloClassFeeEventID_EVENT_SYSTEM_ADD: return @"ApolloClassFeeEventID_EVENT_SYSTEM_ADD";
        case ApolloClassFeeEventID_EVENT_DONATE_CLASS_CARD: return @"ApolloClassFeeEventID_EVENT_DONATE_CLASS_CARD";
        case ApolloClassFeeEventID_EVENT_QUESTIONNAIRE_SUBMITTED: return @"ApolloClassFeeEventID_EVENT_QUESTIONNAIRE_SUBMITTED";
        case ApolloClassFeeEventID_EVENT_SEND_SMS: return @"ApolloClassFeeEventID_EVENT_SEND_SMS";
        case ApolloClassFeeEventID_EVENT_MALL_CONSUME: return @"ApolloClassFeeEventID_EVENT_MALL_CONSUME";
        case ApolloClassFeeEventID_EVENT_MALL_ROLLBACK: return @"ApolloClassFeeEventID_EVENT_MALL_ROLLBACK";
        default: return @"";
    }
}

+ (ApolloClassFeeEventID)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_CREATE")) return ApolloClassFeeEventID_EVENT_CREATE;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_ACTIVE")) return ApolloClassFeeEventID_EVENT_ACTIVE;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_ADVERT")) return ApolloClassFeeEventID_EVENT_ADVERT;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_DEPOSIT")) return ApolloClassFeeEventID_EVENT_DEPOSIT;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_ROLLBACK")) return ApolloClassFeeEventID_EVENT_ROLLBACK;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_OWN_ADVERT")) return ApolloClassFeeEventID_EVENT_OWN_ADVERT;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_SYSTEM_ADD")) return ApolloClassFeeEventID_EVENT_SYSTEM_ADD;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_DONATE_CLASS_CARD")) return ApolloClassFeeEventID_EVENT_DONATE_CLASS_CARD;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_QUESTIONNAIRE_SUBMITTED")) return ApolloClassFeeEventID_EVENT_QUESTIONNAIRE_SUBMITTED;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_SEND_SMS")) return ApolloClassFeeEventID_EVENT_SEND_SMS;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_MALL_CONSUME")) return ApolloClassFeeEventID_EVENT_MALL_CONSUME;
    if(isJceEnumStringEqual(s, @"ApolloClassFeeEventID_EVENT_MALL_ROLLBACK")) return ApolloClassFeeEventID_EVENT_MALL_ROLLBACK;
    return NSIntegerMin;
}

@end

#endif
