// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpProto.jce'
// **********************************************************************

#import "ApolloTHttpPackage.h"

@implementation ApolloTHttpPackage

@synthesize JV2_PROP_NM(r,0,sVer);
@synthesize JV2_PROP_NM(r,1,nClientType);
@synthesize JV2_PROP_NM(r,2,uid);
@synthesize JV2_PROP_NM(r,3,nCMDID);
@synthesize JV2_PROP_NM(r,4,iSequence);
@synthesize JV2_PROP_NM(r,5,vecData);
@synthesize JV2_PROP_NM(o,6,sToken);

+ (void)initialize
{
    if (self == [ApolloTHttpPackage class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(sVer) = DefaultJceString;
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(vecData) = DefaultJceData;
        JV2_PROP(sToken) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.THttpPackage";
}

@end
