// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTStructUserSchool : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(sid,setSid:)) JceInt32 JV2_PROP_NM(r,1,sid);
@property (nonatomic, retain, JV2_PROP_GS_V2(schoolName,setSchoolName:)) NSString* JV2_PROP_NM(r,2,schoolName);

@end
