// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqOmsEditTeacher.h"

@implementation ApolloTReqOmsEditTeacher

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_EX(r,2,vItem,VOApolloTEditTeacherClassItem);

+ (void)initialize
{
    if (self == [ApolloTReqOmsEditTeacher class]) {
        [ApolloTEditTeacherClassItem initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(vItem) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqOmsEditTeacher";
}

@end
