// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTZoneRecord.h"

@implementation ApolloTZoneRecord

@synthesize JV2_PROP_NM(r,0,index);
@synthesize JV2_PROP_NM(r,1,type);
@synthesize JV2_PROP_NM(o,2,zone);
@synthesize JV2_PROP_NM(o,3,comment);
@synthesize JV2_PROP_NM(o,4,msg);
@synthesize JV2_PROP_NM(o,5,title);

+ (void)initialize
{
    if (self == [ApolloTZoneRecord class]) {
        [ApolloTZoneComment initialize];
        [ApolloTZoneMsg initialize];
        [ApolloTZoneObject initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(title) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TZoneRecord";
}

@end
