// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTNoticeReadTime : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iNoticeId,setINoticeId:)) JceInt64 JV2_PROP_NM(r,0,iNoticeId);
@property (nonatomic, assign, JV2_PROP_GS_V2(readTime,setReadTime:)) JceInt64 JV2_PROP_NM(r,1,readTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(userid,setUserid:)) NSString* JV2_PROP_NM(r,2,userid);
@property (nonatomic, retain, JV2_PROP_GS_V2(tagid,setTagid:)) NSString* JV2_PROP_NM(r,3,tagid);

@end
