// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Package.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloEMSG_TYPE_MSGTYPE_NULL = 0,
    ApolloEMSG_TYPE_MSGTYPE_REQUEST,
    ApolloEMSG_TYPE_MSGTYPE_RESPONSE,
    ApolloEMSG_TYPE_MSGTYPE_NOTIFY,
    ApolloEMSG_TYPE_MSGTYPE_NOTIFY_ACK,
    ApolloEMSG_TYPE_MSGTYPE_SERVER_REQ,
    ApolloEMSG_TYPE_MSGTYPE_SERVER_RESP
};
#define ApolloEMSG_TYPE NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloEMSG_TYPEHelper: JceEnumHelper

+ (NSString *)etos:(ApolloEMSG_TYPE)e;
+ (ApolloEMSG_TYPE)stoe:(NSString *)s;

@end

#endif
