// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTRecFamily.h"

@interface ApolloTRecUserInfo : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(identity,setIdentity:)) JceInt16 JV2_PROP_NM(r,2,identity);
@property (nonatomic, retain, JV2_PROP_GS_V2(vecFamily,setVecFamily:)) NSArray* JV2_PROP_EX(r,3,vecFamily,VOApolloTRecFamily);
@property (nonatomic, retain, JV2_PROP_GS_V2(mobilePhone,setMobilePhone:)) NSString* JV2_PROP_NM(r,4,mobilePhone);

@end
