// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTUserInfoForSendSysNotice.h"

@implementation ApolloTUserInfoForSendSysNotice

@synthesize JV2_PROP_NM(r,0,masterName);
@synthesize JV2_PROP_NM(r,1,masterIcon);
@synthesize JV2_PROP_NM(r,2,userName);
@synthesize JV2_PROP_NM(r,3,userIcon);
@synthesize JV2_PROP_NM(r,4,student);
@synthesize JV2_PROP_NM(r,5,masterUid);

+ (void)initialize
{
    if (self == [ApolloTUserInfoForSendSysNotice class]) {
        [ApolloTStudent initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(masterName) = DefaultJceString;
        JV2_PROP(masterIcon) = DefaultJceString;
        JV2_PROP(userName) = DefaultJceString;
        JV2_PROP(userIcon) = DefaultJceString;
        JV2_PROP(student) = [ApolloTStudent object];
        JV2_PROP(masterUid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TUserInfoForSendSysNotice";
}

@end
