// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqDelFocusChild.h"

@implementation ApolloTReqDelFocusChild

@synthesize JV2_PROP_NM(r,0,childid);

+ (void)initialize
{
    if (self == [ApolloTReqDelFocusChild class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(childid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqDelFocusChild";
}

@end
