// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTReqPersonHomePageLikeList.h"

@implementation ApolloTReqPersonHomePageLikeList

@synthesize JV2_PROP_NM(r,0,flag);
@synthesize JV2_PROP_NM(r,1,index);

+ (void)initialize
{
    if (self == [ApolloTReqPersonHomePageLikeList class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqPersonHomePageLikeList";
}

@end
