// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqIncome : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(strName,setStrName:)) NSString* JV2_PROP_NM(r,1,strName);
@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(r,2,cid);
@property (nonatomic, assign, JV2_PROP_GS_V2(sEventID,setSEventID:)) JceInt16 JV2_PROP_NM(r,3,sEventID);
@property (nonatomic, assign, JV2_PROP_GS_V2(iAdNo,setIAdNo:)) JceInt32 JV2_PROP_NM(o,4,iAdNo);
@property (nonatomic, assign, JV2_PROP_GS_V2(iAdID,setIAdID:)) JceInt32 JV2_PROP_NM(o,5,iAdID);
@property (nonatomic, assign, JV2_PROP_GS_V2(money,setMoney:)) JceInt64 JV2_PROP_NM(o,6,money);
@property (nonatomic, retain, JV2_PROP_GS_V2(remark,setRemark:)) NSString* JV2_PROP_NM(o,7,remark);

@end
