// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneLikerObject.h"

@interface ApolloTZoneLikerListUser : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt64 JV2_PROP_NM(o,0,index);
@property (nonatomic, retain, JV2_PROP_GS_V2(userObj,setUserObj:)) ApolloTZoneLikerObject* JV2_PROP_NM(r,1,userObj);

@end
