// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTSingleStudentParentItem : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(mobile,setMobile:)) NSString* JV2_PROP_NM(r,0,mobile);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(role,setRole:)) NSString* JV2_PROP_NM(r,2,role);
@property (nonatomic, assign, JV2_PROP_GS_V2(main,setMain:)) JceInt32 JV2_PROP_NM(r,3,main);

@end
