// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqOmsExitClass.h"

@implementation ApolloTReqOmsExitClass

@synthesize JV2_PROP_NM(r,0,flag);
@synthesize JV2_PROP_NM(r,1,cid);
@synthesize JV2_PROP_NM(r,2,uid);

+ (void)initialize
{
    if (self == [ApolloTReqOmsExitClass class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqOmsExitClass";
}

@end
