// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "ApolloTReqCaifutongBatchPay.h"

@implementation ApolloTReqCaifutongBatchPay

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,strName);
@synthesize JV2_PROP_NM(r,2,cid);
@synthesize JV2_PROP_NM(r,3,dValue);
@synthesize JV2_PROP_NM(r,4,banktype);
@synthesize JV2_PROP_NM(r,5,area);
@synthesize JV2_PROP_NM(r,6,city);
@synthesize JV2_PROP_NM(r,7,subbankname);
@synthesize JV2_PROP_NM(r,8,username);
@synthesize JV2_PROP_NM(r,9,usercard);
@synthesize JV2_PROP_NM(r,10,bankaccount);
@synthesize JV2_PROP_NM(r,11,desc);
@synthesize JV2_PROP_NM(r,12,recmobile);
@synthesize JV2_PROP_NM(r,13,acctype);

+ (void)initialize
{
    if (self == [ApolloTReqCaifutongBatchPay class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(strName) = DefaultJceString;
        JV2_PROP(banktype) = DefaultJceString;
        JV2_PROP(area) = DefaultJceString;
        JV2_PROP(city) = DefaultJceString;
        JV2_PROP(subbankname) = DefaultJceString;
        JV2_PROP(username) = DefaultJceString;
        JV2_PROP(usercard) = DefaultJceString;
        JV2_PROP(bankaccount) = DefaultJceString;
        JV2_PROP(desc) = DefaultJceString;
        JV2_PROP(recmobile) = DefaultJceString;
        JV2_PROP(acctype) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqCaifutongBatchPay";
}

@end
