// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTTeacherItem.h"

@implementation ApolloTTeacherItem

@synthesize JV2_PROP_NM(r,0,name);
@synthesize JV2_PROP_NM(r,1,mobilephone);

+ (void)initialize
{
    if (self == [ApolloTTeacherItem class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(mobilephone) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TTeacherItem";
}

@end
