// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTClassFeeCard.h"

@interface ApolloTRespBindClassFeeCard : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(card,setCard:)) ApolloTClassFeeCard* JV2_PROP_NM(r,0,card);

@end
