// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqAddChildFocusUser.h"

@implementation ApolloTReqAddChildFocusUser

@synthesize JV2_PROP_NM(r,0,childUid);
@synthesize JV2_PROP_NM(r,1,mobilephone);
@synthesize JV2_PROP_NM(r,2,role);

+ (void)initialize
{
    if (self == [ApolloTReqAddChildFocusUser class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(childUid) = DefaultJceString;
        JV2_PROP(mobilephone) = DefaultJceString;
        JV2_PROP(role) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqAddChildFocusUser";
}

@end
