// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "ApolloTReqWeiXiNotifyResult.h"

@implementation ApolloTReqWeiXiNotifyResult

@synthesize JV2_PROP_NM(r,0,appid);
@synthesize JV2_PROP_NM(r,1,mch_id);
@synthesize JV2_PROP_NM(r,2,nonce_str);
@synthesize JV2_PROP_NM(r,3,sign);
@synthesize JV2_PROP_NM(r,4,result_code);
@synthesize JV2_PROP_NM(r,5,openid);
@synthesize JV2_PROP_NM(r,6,trade_type);
@synthesize JV2_PROP_NM(r,7,bank_type);
@synthesize JV2_PROP_NM(r,8,total_fee);
@synthesize JV2_PROP_NM(r,9,cash_fee);
@synthesize JV2_PROP_NM(r,10,transaction_id);
@synthesize JV2_PROP_NM(r,11,out_trade_no);
@synthesize JV2_PROP_NM(r,12,time_end);

+ (void)initialize
{
    if (self == [ApolloTReqWeiXiNotifyResult class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(appid) = DefaultJceString;
        JV2_PROP(mch_id) = DefaultJceString;
        JV2_PROP(nonce_str) = DefaultJceString;
        JV2_PROP(sign) = DefaultJceString;
        JV2_PROP(result_code) = DefaultJceString;
        JV2_PROP(openid) = DefaultJceString;
        JV2_PROP(trade_type) = DefaultJceString;
        JV2_PROP(bank_type) = DefaultJceString;
        JV2_PROP(total_fee) = DefaultJceString;
        JV2_PROP(cash_fee) = DefaultJceString;
        JV2_PROP(transaction_id) = DefaultJceString;
        JV2_PROP(out_trade_no) = DefaultJceString;
        JV2_PROP(time_end) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqWeiXiNotifyResult";
}

@end
