// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTRespZones.h"

@implementation ApolloTRespZones

@synthesize JV2_PROP_EX(r,0,zones,VOApolloTZoneObject);

+ (void)initialize
{
    if (self == [ApolloTRespZones class]) {
        [ApolloTZoneObject initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(zones) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespZones";
}

@end
