// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqChildTestJoinClass : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(studentuid,setStudentuid:)) NSString* JV2_PROP_NM(r,0,studentuid);
@property (nonatomic, retain, JV2_PROP_GS_V2(studentname,setStudentname:)) NSString* JV2_PROP_NM(r,1,studentname);
@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(r,2,cid);

@end
