// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTReceiverObject.h"

@implementation ApolloTReceiverObject

@synthesize JV2_PROP_NM(r,0,iType);
@synthesize JV2_PROP_NM(r,1,objectId);
@synthesize JV2_PROP_NM(o,2,uid);

+ (void)initialize
{
    if (self == [ApolloTReceiverObject class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(objectId) = DefaultJceString;
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReceiverObject";
}

@end
