// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespTotalMoneyAndHead : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(totalMoney,setTotalMoney:)) JceInt32 JV2_PROP_NM(r,0,totalMoney);
@property (nonatomic, assign, JV2_PROP_GS_V2(totalHead,setTotalHead:)) JceInt32 JV2_PROP_NM(r,1,totalHead);

@end
