// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTReqSendSystemTeamMessageToSpecialUser.h"

@implementation ApolloTReqSendSystemTeamMessageToSpecialUser

@synthesize JV2_PROP_NM(o,0,Message);
@synthesize JV2_PROP_NM(o,1,type);
@synthesize JV2_PROP_EX(o,2,vPhoneNumOrUserIdsStr,VONSString);

+ (void)initialize
{
    if (self == [ApolloTReqSendSystemTeamMessageToSpecialUser class]) {
        [ApolloTNotice initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSendSystemTeamMessageToSpecialUser";
}

@end
