// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneCommentContent.h"

@interface ApolloTZoneComment : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(commentId,setCommentId:)) JceInt64 JV2_PROP_NM(r,0,commentId);
@property (nonatomic, retain, JV2_PROP_GS_V2(content,setContent:)) ApolloTZoneCommentContent* JV2_PROP_NM(r,1,content);
@property (nonatomic, assign, JV2_PROP_GS_V2(sendTime,setSendTime:)) JceInt64 JV2_PROP_NM(r,2,sendTime);
@property (nonatomic, assign, JV2_PROP_GS_V2(hot,setHot:)) JceInt32 JV2_PROP_NM(r,3,hot);
@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt64 JV2_PROP_NM(r,4,index);
@property (nonatomic, assign, JV2_PROP_GS_V2(likeStatus,setLikeStatus:)) JceInt32 JV2_PROP_NM(o,5,likeStatus);

@end
