// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Adapte.jce'
// **********************************************************************

#import "ApolloTWebImportStudentGuardianItem.h"

@implementation ApolloTWebImportStudentGuardianItem

@synthesize JV2_PROP_NM(r,0,studentName);
@synthesize JV2_PROP_NM(r,1,mobilePhone);
@synthesize JV2_PROP_EX(o,2,vMobilePhones,VONSString);

+ (void)initialize
{
    if (self == [ApolloTWebImportStudentGuardianItem class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(studentName) = DefaultJceString;
        JV2_PROP(mobilePhone) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TWebImportStudentGuardianItem";
}

@end
