// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFee.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTClassFeeLog.h"

@interface ApolloTRespClassFeeDetail : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(vLog,setVLog:)) NSArray* JV2_PROP_EX(r,0,vLog,VOApolloTClassFeeLog);

@end
