// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTThirdAccount : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(flag,setFlag:)) JceInt32 JV2_PROP_NM(r,0,flag);
@property (nonatomic, retain, JV2_PROP_GS_V2(threeuserid,setThreeuserid:)) NSString* JV2_PROP_NM(r,1,threeuserid);
@property (nonatomic, retain, JV2_PROP_GS_V2(threeusername,setThreeusername:)) NSString* JV2_PROP_NM(r,2,threeusername);

@end
