// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqJoinClass : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(cid,setCid:)) JceInt32 JV2_PROP_NM(r,0,cid);
@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,1,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt16 JV2_PROP_NM(r,2,type);
@property (nonatomic, retain, JV2_PROP_GS_V2(classCode,setClassCode:)) NSString* JV2_PROP_NM(o,3,classCode);
@property (nonatomic, retain, JV2_PROP_GS_V2(studentName,setStudentName:)) NSString* JV2_PROP_NM(o,4,studentName);
@property (nonatomic, retain, JV2_PROP_GS_V2(relation,setRelation:)) NSString* JV2_PROP_NM(o,5,relation);
@property (nonatomic, retain, JV2_PROP_GS_V2(subjectName,setSubjectName:)) NSString* JV2_PROP_NM(o,6,subjectName);
@property (nonatomic, retain, JV2_PROP_GS_V2(studentId,setStudentId:)) NSString* JV2_PROP_NM(o,7,studentId);

@end
