// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespClassFeeCardRollout : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(iRet,setIRet:)) JceInt32 JV2_PROP_NM(r,0,iRet);
@property (nonatomic, retain, JV2_PROP_GS_V2(strMsg,setStrMsg:)) NSString* JV2_PROP_NM(r,1,strMsg);
@property (nonatomic, assign, JV2_PROP_GS_V2(lOrderNum,setLOrderNum:)) JceInt64 JV2_PROP_NM(o,2,lOrderNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(amount,setAmount:)) JceInt32 JV2_PROP_NM(o,3,amount);

@end
