// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqSetSubject.h"

@implementation ApolloTReqSetSubject

@synthesize JV2_PROP_NM(r,0,cid);
@synthesize JV2_PROP_NM(r,2,teacherId);
@synthesize JV2_PROP_NM(r,3,newSubject);

+ (void)initialize
{
    if (self == [ApolloTReqSetSubject class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(teacherId) = DefaultJceString;
        JV2_PROP(newSubject) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSetSubject";
}

@end
