// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTZoneMessage.h"

@implementation ApolloTZoneMessage

@synthesize JV2_PROP_NM(r,0,mid);
@synthesize JV2_PROP_NM(r,1,type);
@synthesize JV2_PROP_NM(r,2,action);
@synthesize JV2_PROP_NM(r,3,msgid);
@synthesize JV2_PROP_NM(r,4,content);
@synthesize JV2_PROP_NM(r,5,sender);
@synthesize JV2_PROP_NM(o,6,sendertime);
@synthesize JV2_PROP_NM(o,7,iNewArrival);

+ (void)initialize
{
    if (self == [ApolloTZoneMessage class]) {
        [ApolloTZoneSenderObject initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(msgid) = DefaultJceString;
        JV2_PROP(content) = DefaultJceString;
        JV2_PROP(sender) = [ApolloTZoneSenderObject object];
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TZoneMessage";
}

@end
