// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqSetPersonalInfo : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(flag,setFlag:)) JceInt32 JV2_PROP_NM(r,1,flag);
@property (nonatomic, retain, JV2_PROP_GS_V2(photo,setPhoto:)) NSString* JV2_PROP_NM(r,2,photo);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,3,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(sex,setSex:)) JceInt16 JV2_PROP_NM(r,4,sex);
@property (nonatomic, assign, JV2_PROP_GS_V2(address,setAddress:)) JceInt32 JV2_PROP_NM(r,5,address);
@property (nonatomic, retain, JV2_PROP_GS_V2(desc,setDesc:)) NSString* JV2_PROP_NM(r,6,desc);

@end
