// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTAuthTeacherApplication : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(id,setId:)) JceInt32 JV2_PROP_NM(r,0,id);
@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,1,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,2,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(mobilePhone,setMobilePhone:)) NSString* JV2_PROP_NM(r,3,mobilePhone);
@property (nonatomic, assign, JV2_PROP_GS_V2(sex,setSex:)) JceInt16 JV2_PROP_NM(r,4,sex);
@property (nonatomic, retain, JV2_PROP_GS_V2(pic,setPic:)) NSString* JV2_PROP_NM(r,5,pic);
@property (nonatomic, assign, JV2_PROP_GS_V2(creationtime,setCreationtime:)) JceInt64 JV2_PROP_NM(r,6,creationtime);
@property (nonatomic, assign, JV2_PROP_GS_V2(audittime,setAudittime:)) JceInt64 JV2_PROP_NM(r,7,audittime);
@property (nonatomic, assign, JV2_PROP_GS_V2(auditstatus,setAuditstatus:)) JceInt16 JV2_PROP_NM(r,8,auditstatus);
@property (nonatomic, retain, JV2_PROP_GS_V2(desc,setDesc:)) NSString* JV2_PROP_NM(r,9,desc);

@end
