// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Package.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTOpenStatus.h"

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@implementation ApolloTOpenStatusHelper

+ (NSString *)etos:(ApolloTOpenStatus)e
{
    switch(e){
        case ApolloTOpenStatus_OPEN_ALL: return @"ApolloTOpenStatus_OPEN_ALL";
        case ApolloTOpenStatus_OPEN_CLASS: return @"ApolloTOpenStatus_OPEN_CLASS";
        default: return @"";
    }
}

+ (ApolloTOpenStatus)stoe:(NSString *)s
{
    if(isJceEnumStringEqual(s, @"ApolloTOpenStatus_OPEN_ALL")) return ApolloTOpenStatus_OPEN_ALL;
    if(isJceEnumStringEqual(s, @"ApolloTOpenStatus_OPEN_CLASS")) return ApolloTOpenStatus_OPEN_CLASS;
    return NSIntegerMin;
}

@end

#endif
