// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloENoticeType_ESYSTEM = 0,
    ApolloENoticeType_EHOMEWORK = 1,
    ApolloENoticeType_EGUARDIAN_NOTIFY = 2,
    ApolloENoticeType_ESCHOOL_EXPRESSION = 3,
    ApolloENoticeType_EURDENCY_NOTIFY = 4,
    ApolloENoticeType_ESCORE_NOTIFY = 5,
    ApolloENoticeType_EINVITE = 6,
    ApolloENoticeType_ETEACHER_NOTIFY = 7,
    ApolloENoticeType_EMENU = 8
};
#define ApolloENoticeType NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloENoticeTypeHelper: JceEnumHelper

+ (NSString *)etos:(ApolloENoticeType)e;
+ (ApolloENoticeType)stoe:(NSString *)s;

@end

#endif
