// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTUserLabel.h"

@interface ApolloTZonePerson : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,1,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(sex,setSex:)) JceInt16 JV2_PROP_NM(r,2,sex);
@property (nonatomic, assign, JV2_PROP_GS_V2(identity,setIdentity:)) JceInt32 JV2_PROP_NM(r,3,identity);
@property (nonatomic, assign, JV2_PROP_GS_V2(teacherauth,setTeacherauth:)) JceInt16 JV2_PROP_NM(r,4,teacherauth);
@property (nonatomic, retain, JV2_PROP_GS_V2(address,setAddress:)) NSString* JV2_PROP_NM(r,5,address);
@property (nonatomic, retain, JV2_PROP_GS_V2(photo,setPhoto:)) NSString* JV2_PROP_NM(r,6,photo);
@property (nonatomic, retain, JV2_PROP_GS_V2(userdesc,setUserdesc:)) NSString* JV2_PROP_NM(o,7,userdesc);
@property (nonatomic, retain, JV2_PROP_GS_V2(vLabels,setVLabels:)) NSArray* JV2_PROP_EX(o,8,vLabels,VOApolloTUserLabel);

@end
