// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTGetZoneMsgType.h"

@interface ApolloTReqZoneMsg : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt64 JV2_PROP_NM(r,1,index);
@property (nonatomic, assign, JV2_PROP_GS_V2(flag,setFlag:)) JceInt32 JV2_PROP_NM(r,2,flag);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) ApolloTGetZoneMsgType JV2_PROP_NM(r,3,type);
@property (nonatomic, retain, JV2_PROP_GS_V2(tagId,setTagId:)) NSString* JV2_PROP_NM(o,4,tagId);

@end
