// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqSMSHideContent : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,0,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(objectid,setObjectid:)) JceInt64 JV2_PROP_NM(r,1,objectid);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt32 JV2_PROP_NM(r,2,type);
@property (nonatomic, assign, JV2_PROP_GS_V2(hide,setHide:)) JceInt32 JV2_PROP_NM(r,3,hide);

@end
