// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqUnlockBindingAccount.h"

@implementation ApolloTReqUnlockBindingAccount

@synthesize JV2_PROP_NM(r,0,flag);

+ (void)initialize
{
    if (self == [ApolloTReqUnlockBindingAccount class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqUnlockBindingAccount";
}

@end
