// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/connect.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqLogout : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(nClientType,setNClientType:)) JceInt16 JV2_PROP_NM(r,0,nClientType);

@end
