// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZoneAction.h"
#import "ApolloTZoneSenderObject.h"

@interface ApolloTZoneObject : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(zid,setZid:)) JceInt64 JV2_PROP_NM(r,0,zid);
@property (nonatomic, retain, JV2_PROP_GS_V2(title,setTitle:)) NSString* JV2_PROP_NM(r,1,title);
@property (nonatomic, retain, JV2_PROP_GS_V2(summary,setSummary:)) NSString* JV2_PROP_NM(r,2,summary);
@property (nonatomic, assign, JV2_PROP_GS_V2(hot,setHot:)) JceInt32 JV2_PROP_NM(r,3,hot);
@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt32 JV2_PROP_NM(r,4,type);
@property (nonatomic, retain, JV2_PROP_GS_V2(pic,setPic:)) NSString* JV2_PROP_NM(r,5,pic);
@property (nonatomic, assign, JV2_PROP_GS_V2(likeNum,setLikeNum:)) JceInt32 JV2_PROP_NM(r,6,likeNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(shareNum,setShareNum:)) JceInt32 JV2_PROP_NM(r,7,shareNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(msgNum,setMsgNum:)) JceInt32 JV2_PROP_NM(r,8,msgNum);
@property (nonatomic, retain, JV2_PROP_GS_V2(url,setUrl:)) NSString* JV2_PROP_NM(r,9,url);
@property (nonatomic, assign, JV2_PROP_GS_V2(urlType,setUrlType:)) JceInt32 JV2_PROP_NM(r,10,urlType);
@property (nonatomic, retain, JV2_PROP_GS_V2(action,setAction:)) ApolloTZoneAction* JV2_PROP_NM(r,11,action);
@property (nonatomic, assign, JV2_PROP_GS_V2(publishTime,setPublishTime:)) JceInt64 JV2_PROP_NM(r,12,publishTime);
@property (nonatomic, retain, JV2_PROP_GS_V2(sender,setSender:)) ApolloTZoneSenderObject* JV2_PROP_NM(r,13,sender);
@property (nonatomic, retain, JV2_PROP_GS_V2(tag,setTag:)) NSString* JV2_PROP_NM(r,14,tag);
@property (nonatomic, assign, JV2_PROP_GS_V2(opentype,setOpentype:)) JceInt32 JV2_PROP_NM(r,15,opentype);
@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt32 JV2_PROP_NM(o,16,index);
@property (nonatomic, retain, JV2_PROP_GS_V2(icon,setIcon:)) NSString* JV2_PROP_NM(o,17,icon);
@property (nonatomic, assign, JV2_PROP_GS_V2(picHeight,setPicHeight:)) JceInt32 JV2_PROP_NM(o,18,picHeight);
@property (nonatomic, assign, JV2_PROP_GS_V2(picWidth,setPicWidth:)) JceInt32 JV2_PROP_NM(o,19,picWidth);

@end
