// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespWeiXiQueryOrder : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(result_code,setResult_code:)) NSString* JV2_PROP_NM(r,0,result_code);
@property (nonatomic, retain, JV2_PROP_GS_V2(trade_type,setTrade_type:)) NSString* JV2_PROP_NM(r,1,trade_type);
@property (nonatomic, retain, JV2_PROP_GS_V2(trade_state,setTrade_state:)) NSString* JV2_PROP_NM(r,2,trade_state);
@property (nonatomic, retain, JV2_PROP_GS_V2(bank_type,setBank_type:)) NSString* JV2_PROP_NM(r,3,bank_type);
@property (nonatomic, assign, JV2_PROP_GS_V2(total_fee,setTotal_fee:)) JceInt32 JV2_PROP_NM(r,4,total_fee);
@property (nonatomic, retain, JV2_PROP_GS_V2(transaction_id,setTransaction_id:)) NSString* JV2_PROP_NM(r,5,transaction_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(out_trade_no,setOut_trade_no:)) NSString* JV2_PROP_NM(r,6,out_trade_no);
@property (nonatomic, retain, JV2_PROP_GS_V2(time_end,setTime_end:)) NSString* JV2_PROP_NM(r,7,time_end);
@property (nonatomic, retain, JV2_PROP_GS_V2(trade_state_desc,setTrade_state_desc:)) NSString* JV2_PROP_NM(r,8,trade_state_desc);

@end
