// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqCommentList : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(msgId,setMsgId:)) JceInt64 JV2_PROP_NM(r,0,msgId);
@property (nonatomic, assign, JV2_PROP_GS_V2(index,setIndex:)) JceInt32 JV2_PROP_NM(r,1,index);
@property (nonatomic, assign, JV2_PROP_GS_V2(flag,setFlag:)) JceInt32 JV2_PROP_NM(r,2,flag);

@end
