// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/bank.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqWeiXiRefundOrder : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(transaction_id,setTransaction_id:)) NSString* JV2_PROP_NM(o,0,transaction_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(out_trade_no,setOut_trade_no:)) NSString* JV2_PROP_NM(r,1,out_trade_no);
@property (nonatomic, retain, JV2_PROP_GS_V2(out_refund_no,setOut_refund_no:)) NSString* JV2_PROP_NM(r,2,out_refund_no);
@property (nonatomic, assign, JV2_PROP_GS_V2(total_fee,setTotal_fee:)) JceInt32 JV2_PROP_NM(r,3,total_fee);
@property (nonatomic, assign, JV2_PROP_GS_V2(refund_fee,setRefund_fee:)) JceInt32 JV2_PROP_NM(r,4,refund_fee);

@end
