// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTClass.h"

@interface ApolloTClassGroup : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,0,name);
@property (nonatomic, retain, JV2_PROP_GS_V2(vClasses,setVClasses:)) NSArray* JV2_PROP_EX(r,1,vClasses,VOApolloTClass);
@property (nonatomic, retain, JV2_PROP_GS_V2(childId,setChildId:)) NSString* JV2_PROP_NM(o,2,childId);

@end
