// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTRespPublishZone : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(zid,setZid:)) JceInt64 JV2_PROP_NM(r,0,zid);

@end
