// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "ApolloTZoneMsgContent.h"

@implementation ApolloTZoneMsgContent

@synthesize JV2_PROP_EX(r,0,content,VOApolloTZonePictureText);
@synthesize JV2_PROP_NM(o,1,toClass);
@synthesize JV2_PROP_NM(o,2,openStatus);
@synthesize JV2_PROP_NM(o,3,tagid);

+ (void)initialize
{
    if (self == [ApolloTZoneMsgContent class]) {
        [ApolloTZoneObject initialize];
        [ApolloTZonePictureText initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(content) = DefaultJceArray;
        JV2_PROP(tagid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TZoneMsgContent";
}

@end
