// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTUserLabel : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(id,setId:)) JceInt32 JV2_PROP_NM(r,0,id);
@property (nonatomic, retain, JV2_PROP_GS_V2(text,setText:)) NSString* JV2_PROP_NM(r,1,text);

@end
