// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqCreateClass : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(name,setName:)) NSString* JV2_PROP_NM(r,0,name);
@property (nonatomic, assign, JV2_PROP_GS_V2(sid,setSid:)) JceInt32 JV2_PROP_NM(o,1,sid);
@property (nonatomic, assign, JV2_PROP_GS_V2(grade,setGrade:)) JceInt32 JV2_PROP_NM(o,2,grade);

@end
