// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/zone.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "ApolloTZonePerson.h"
#import "ApolloTZoneRecord.h"

@interface ApolloTRespPersonHomePage : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(person,setPerson:)) ApolloTZonePerson* JV2_PROP_NM(r,0,person);
@property (nonatomic, assign, JV2_PROP_GS_V2(recordNum,setRecordNum:)) JceInt32 JV2_PROP_NM(r,1,recordNum);
@property (nonatomic, retain, JV2_PROP_GS_V2(recordContent,setRecordContent:)) NSArray* JV2_PROP_EX(r,2,recordContent,VOApolloTZoneRecord);
@property (nonatomic, assign, JV2_PROP_GS_V2(likeNum,setLikeNum:)) JceInt32 JV2_PROP_NM(r,3,likeNum);
@property (nonatomic, assign, JV2_PROP_GS_V2(likeStatus,setLikeStatus:)) JceInt32 JV2_PROP_NM(r,4,likeStatus);

@end
