// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTUserInfo.h"

@implementation ApolloTUserInfo

@synthesize JV2_PROP_NM(r,0,uid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_NM(r,2,sex);
@synthesize JV2_PROP_NM(r,3,mobilephone);
@synthesize JV2_PROP_NM(r,4,icon);
@synthesize JV2_PROP_NM(r,5,teacherauth);
@synthesize JV2_PROP_NM(r,6,address);
@synthesize JV2_PROP_NM(r,7,signature);
@synthesize JV2_PROP_NM(r,8,issmsauth);
@synthesize JV2_PROP_NM(r,9,usertype);
@synthesize JV2_PROP_NM(r,10,photo);
@synthesize JV2_PROP_NM(r,11,pingyin);
@synthesize JV2_PROP_NM(o,12,birthday);
@synthesize JV2_PROP_NM(o,13,banbanno);
@synthesize JV2_PROP_NM(o,14,userdesc);

+ (void)initialize
{
    if (self == [ApolloTUserInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(uid) = DefaultJceString;
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(mobilephone) = DefaultJceString;
        JV2_PROP(signature) = DefaultJceString;
        JV2_PROP(photo) = DefaultJceString;
        JV2_PROP(pingyin) = DefaultJceString;
        JV2_PROP(banbanno) = DefaultJceString;
        JV2_PROP(userdesc) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TUserInfo";
}

@end
