// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTReqFocusInChild : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(childid,setChildid:)) NSString* JV2_PROP_NM(r,0,childid);
@property (nonatomic, retain, JV2_PROP_GS_V2(role,setRole:)) NSString* JV2_PROP_NM(r,1,role);

@end
