// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/Adapte.jce'
// **********************************************************************

#import "ApolloTRespWebImportStudentGuardianIntoClass.h"

@implementation ApolloTRespWebImportStudentGuardianIntoClass

@synthesize JV2_PROP_NM(r,0,studentCount);
@synthesize JV2_PROP_NM(r,1,guardianCount);

+ (void)initialize
{
    if (self == [ApolloTRespWebImportStudentGuardianIntoClass class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespWebImportStudentGuardianIntoClass";
}

@end
