// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTRespGetParentChildren.h"

@implementation ApolloTRespGetParentChildren

@synthesize JV2_PROP_EX(r,0,vMyChildren,VOApolloTMyChild);
@synthesize JV2_PROP_EX(r,1,vFocusChildren,VOApolloTMyChild);

+ (void)initialize
{
    if (self == [ApolloTRespGetParentChildren class]) {
        [ApolloTMyChild initialize];
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(vMyChildren) = DefaultJceArray;
        JV2_PROP(vFocusChildren) = DefaultJceArray;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetParentChildren";
}

@end
