// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpProto.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface ApolloTHttpPackage : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(sVer,setSVer:)) NSString* JV2_PROP_NM(r,0,sVer);
@property (nonatomic, assign, JV2_PROP_GS_V2(nClientType,setNClientType:)) JceInt16 JV2_PROP_NM(r,1,nClientType);
@property (nonatomic, retain, JV2_PROP_GS_V2(uid,setUid:)) NSString* JV2_PROP_NM(r,2,uid);
@property (nonatomic, assign, JV2_PROP_GS_V2(nCMDID,setNCMDID:)) JceInt32 JV2_PROP_NM(r,3,nCMDID);
@property (nonatomic, assign, JV2_PROP_GS_V2(iSequence,setISequence:)) JceInt64 JV2_PROP_NM(r,4,iSequence);
@property (nonatomic, retain, JV2_PROP_GS_V2(vecData,setVecData:)) NSData* JV2_PROP_NM(r,5,vecData);
@property (nonatomic, retain, JV2_PROP_GS_V2(sToken,setSToken:)) NSString* JV2_PROP_NM(o,6,sToken);

@end
