// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/PullNewUserActivity.jce'
// **********************************************************************

#import "ApolloTPullNewCid.h"

@implementation ApolloTPullNewCid

@synthesize JV2_PROP_NM(r,0,cid);
@synthesize JV2_PROP_NM(r,1,name);

+ (void)initialize
{
    if (self == [ApolloTPullNewCid class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TPullNewCid";
}

@end
