// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/OMSProxy.jce'
// **********************************************************************

#import "ApolloTRespGetQiniuUpToken.h"

@implementation ApolloTRespGetQiniuUpToken

@synthesize JV2_PROP_NM(r,0,token);
@synthesize JV2_PROP_NM(r,1,url);

+ (void)initialize
{
    if (self == [ApolloTRespGetQiniuUpToken class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(token) = DefaultJceString;
        JV2_PROP(url) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TRespGetQiniuUpToken";
}

@end
