// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/ClassFeeCard.jce'
// **********************************************************************

#import "JceObjectV2.h"

enum {
    ApolloCLASS_FEE_CARD_CATEGORY_CLASS_FEE_CARD_UNKNOW = 0,
    ApolloCLASS_FEE_CARD_CATEGORY_CLASS_FEE_CARD_NORMAL = 1,
    ApolloCLASS_FEE_CARD_CATEGORY_CLASS_FEE_CARD_ACTIVE = 2
};
#define ApolloCLASS_FEE_CARD_CATEGORY NSInteger

#if JCEV2_ENUM_ETOS_AND_STOE_SUPPORTED

@interface ApolloCLASS_FEE_CARD_CATEGORYHelper: JceEnumHelper

+ (NSString *)etos:(ApolloCLASS_FEE_CARD_CATEGORY)e;
+ (ApolloCLASS_FEE_CARD_CATEGORY)stoe:(NSString *)s;

@end

#endif
