// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTReqGetNoticeMsg.h"

@implementation ApolloTReqGetNoticeMsg

@synthesize JV2_PROP_NM(r,0,index);
@synthesize JV2_PROP_NM(r,1,targetid);
@synthesize JV2_PROP_NM(r,2,flag);
@synthesize JV2_PROP_NM(r,3,uid);

+ (void)initialize
{
    if (self == [ApolloTReqGetNoticeMsg class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(targetid) = DefaultJceString;
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqGetNoticeMsg";
}

@end
