// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/class.jce'
// **********************************************************************

#import "ApolloTAreaInfo.h"

@implementation ApolloTAreaInfo

@synthesize JV2_PROP_NM(r,0,aid);
@synthesize JV2_PROP_NM(r,1,name);
@synthesize JV2_PROP_NM(r,2,parentid);
@synthesize JV2_PROP_NM(r,3,type);
@synthesize JV2_PROP_NM(r,4,postcode);
@synthesize JV2_PROP_NM(r,5,areacode);
@synthesize JV2_PROP_NM(r,6,path);

+ (void)initialize
{
    if (self == [ApolloTAreaInfo class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(name) = DefaultJceString;
        JV2_PROP(postcode) = DefaultJceString;
        JV2_PROP(areacode) = DefaultJceString;
        JV2_PROP(path) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TAreaInfo";
}

@end
