// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpClass.jce'
// **********************************************************************

#import "ApolloTReqSetStudentNumber.h"

@implementation ApolloTReqSetStudentNumber

@synthesize JV2_PROP_NM(r,0,studentUid);
@synthesize JV2_PROP_NM(r,1,studentNumber);

+ (void)initialize
{
    if (self == [ApolloTReqSetStudentNumber class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(studentUid) = DefaultJceString;
        JV2_PROP(studentNumber) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqSetStudentNumber";
}

@end
