// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/notice.jce'
// **********************************************************************

#import "ApolloTClientReceiveNoticeIndex.h"

@implementation ApolloTClientReceiveNoticeIndex

@synthesize JV2_PROP_NM(r,0,targeterid);
@synthesize JV2_PROP_NM(r,1,index);
@synthesize JV2_PROP_NM(r,2,uid);

+ (void)initialize
{
    if (self == [ApolloTClientReceiveNoticeIndex class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(targeterid) = DefaultJceString;
        JV2_PROP(uid) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TClientReceiveNoticeIndex";
}

@end
