// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.32 by WSRD Tencent.
// Generated from `./jce/HttpProto.jce'
// **********************************************************************

#import "ApolloTReqCheckMobileAuthCode.h"

@implementation ApolloTReqCheckMobileAuthCode

@synthesize JV2_PROP_NM(r,0,mobile);
@synthesize JV2_PROP_NM(r,1,type);
@synthesize JV2_PROP_NM(r,2,code);

+ (void)initialize
{
    if (self == [ApolloTReqCheckMobileAuthCode class]) {
        [super initialize];
    }
}

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(mobile) = DefaultJceString;
        JV2_PROP(code) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Apollo.TReqCheckMobileAuthCode";
}

@end
